### ISSUE TITLE
Clarify usage pattern for read_rest in function hts_itr_next

### ISSUE THREAD

**Issue by shadowtramp** [samtools/hts-specs#101]
Please, clarify the usage of the flag **read_rest**.

It appears to me that idea behind this flag is to make it possible to return the iteration to the previously saved virtual position.

But I see behavior in function **hts_itr_next** that I can not understand. Namely lines:
```
if (iter->read_rest) {
        if (iter->curr_off) { // seek to the start
            bgzf_seek(fp, iter->curr_off, SEEK_SET); 
            iter->curr_off = 0; // only seek once
        }
```
look strange to me. Shouldn't it be something like
```
if (iter->read_rest) {
        if (iter->curr_off) { // seek to the start
            bgzf_seek(fp, iter->curr_off, SEEK_SET); 
            iter->read_rest = 0; // only seek once
        }
```

**Comment by jmarshall** [comment]
`read_rest` simply means "read the rest (i.e., remainder) of the records in the file", rather than doing any further index-based seeking.

It is an internal implementation detail in `hts_itr_t`, so client code using htslib doesn't need to know anything about it.  (And it's certainly nothing to do with **hts-specs**, but I assume you intended to open this against **htslib**.)
