### ISSUE TITLE
Suggestion: add RX and QX tags for molecular barcodes

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#109]
I'd like to add standard tags RX and QX (to the SAM spec) for the bases of a molecular barcode and their qualities as read by the sequencer. 

To be clear, this is _not_ the sample barcode which can be used to demultiplex the sequence data, but rather a molecular barcode/index that can be used to identify the original molecule from which the sequence was generated. This can be used to disambiguate PCR from "Biological" duplicates (say in RNA-seq or other high depth technologies), or to identify the haplotype from whence many read pairs arose (as in 10X technology, e.g.)

There might be a need for other tags for the "corrected" barcode that is identified after comparing with a whitelist, but I'm not including that in this suggestion.

Some discussion of this proposal has started here:  (https://github.com/broadinstitute/picard/issues/287)  

I'd like to here what people think before submitting a PR here.

**Comment by tfenne** [comment]
The discussion in the linked picard issue left it somewhat ambiguous whether or not `BC` and `QT` were also for this purpose.  In my own work I've been using `BC` to store the molecular index, not the sample index.  It would be good to understand if others are also doing this.

**Comment by yfarjoun** [comment]
It seems that as these are different things, they should have different tags. Do you not agree?

**Comment by tfenne** [comment]
I agree that sample index and molecular index are different things.  However the current spec doesn't say "sample" or "molecuar", it just says "barcode".  Since I don't see the utility of stamping the sample barcode on every read, I assumed `BC` was for molecular indices and have been using it that way.  My only real concern is that many others may have done the same, and we'll have some confusion/bifurcation.

**Comment by yfarjoun** [comment]
The place in the code where I see the actual sample-barcode being used in
the BC tag is when there is no good match with the list of provided
barcodes:

// If it's a barcoded run and the read isn't assigned to a barcode, then
add the barcode
// that was read as an optional tag
if (unmatchedBarcode != null) {
    sam.setAttribute(SAMTag.BC.name(), unmatchedBarcode);
}

from picard.illumina.ClusterDataToSamConverter#createSamRecord



On Mon, Nov 16, 2015 at 2:47 PM, Tim Fennell <notifications@github.com>
wrote:
>
> I agree that sample index and molecular index are different things.
However the current spec doesn't say "sample" or "molecuar", it just says
"barcode". Since I don't see the utility of stamping the sample barcode on
every read, I assumed BC was for molecular indices and have been using it
that way. My only real concern is that many others may have done the same,
and we'll have some confusion/bifurcation.

**Comment by mattsooknah** [comment]
Based on @wheaton5 's previous comment, it sounds like 10X is already using RX for the observed long-molecule barcodes and BX for the corrected barcodes. I would be in favor of adding these new, more specific tags to the spec.

For read-specific barcodes (e.g. UMIs), I would even say add another tag (e.g. UX) so we can be as unambiguous as possible.

I'm not sure what we should do about BC, since different people / programs seem to have different use cases. I always thought of it as the sample barcode. But if RX, etc are added, then we should at least add a note to BC saying that more specific tags exist.

**Comment by ablewhiskey** [comment]
Alex from 10X here...

We would propose keeping the usage as BC for sample barcode, and adding BX for molecular barcode.

We think there should be two separate tags, as opposed to overloading the meaning of BC, as it is common for people to want to do long molecule barcoding and sample multiplexing at the same time.

Our BAM files use RX to contain the raw, uncorrected molecular barcode as read from the sequencer. QX is used for the read quality of RX.

We use BX for the error-corrected, whitelist-validated molecular barcode, and those are the barcodes used for all downstream analysis in our pipelines. The BX barcodes include both the sequence and a numeric suffix (e.g. -1, -2) that allows virtualization of barcodes pooled from separate partitioning channels to achieve a higher effective barcode diversity.

**We are actually planning to remove RX and QX from our BAM files in our next release**, as we have found they tend to confuse users and they end up using the raw barcode instead of the corrected barcode. We will just report the corrected BX barcode.

**Comment by nh13** [comment]
@yfarjoun @mattsooknah I would really like `BX` to be specified to be used as the molecular barcode, but I would also like a tag that is a barcode to identify a read, which could be one of many from the given long molecule.  To play Devil's advocate, if `RX` and `QX` will be removed by 10x, why not just use a different read group per long molecule, and store the "corrected" barcode in the read group header line?

**Comment by yfarjoun** [comment]
@nh13, wouldn't what you are advocating lead to headers with ~750K lines?

**Comment by yfarjoun** [comment]
@ablewhiskey Woudn't the corrected Barcode (without -1 -2, etc.) + the library of the readgroup tell you the information contained in the Barcode with -1 -2, etc? I think that the lack of a readgroup tag in your reads is the reason you need the -1, -2 addition. (slightly off topic perhaps)

**Comment by yfarjoun** [comment]
Perhaps the suggested change should be:

RX/QX - concatenation of raw bases/qualities from various barcodes that are _not_ sample barcodes
BX - LongMolecule barcode post whitelisting/error correction and extraction from RX (with or without library-modifier)
UX - UMI after whitelisting/error correction and extraction from RX

Would that allow for all foreseeable use-cases?

**Comment by nh13** [comment]
@yfarjoun RE: many read groups: very true, but for me to figure out the list of possible long molecule barcodes, I would only need to read the header, while otherwise I would have to scan the file, or worse yet, have an auxiliary file.  

@yfarjoun RE: concatenation of barcodes.  This is not useful in the case of multiple barcodes, as then more metadata needs to be stored to say how to partition the bases.  I rather like my idea of a long-molecule barcode (RX/QC) and a per-read (i.e. pre-PCR, post long-molecule) barcode (??/??).

**Comment by yfarjoun** [comment]
@nh13:

1. not sure what the usecase is for knowing in advance the possible long
molecules that doesn't include also scanning through the file.
2. could concatenate with an agreed upon separator (as is currently
implemented for SampleBarcode in IlluminaBaseCallsToSam for the case that
an unknown, multiple barcode is encountered)

**Comment by nh13** [comment]
1. computational performance: certain data stuctures that would store metrics about long molecule barcodes could benefit from knowing how many there are up front.  Lets table this, as I don't think read groups are the right solution (see 2).
2. that's a reasonable compromise, :+1:

**Comment by tfenne** [comment]
Jumping back in, I'd like to try and summarize what I think folks are converging on, to see if I've understood.  It sounds like we're going to have a bunch of new tags, largely to cope with the situation where a library needs to use _all_ of them in order to represent what was made:

1. BC - the barcode sequence that identifies all the reads in the whole library preparation for a single sample.  Will only have one per read group (modulo sequencing errors).  This kind of barcode is used is the majority of sequencing experiments these days, but is often not put into the BAM.
2. BX - a long molecule / sub-library barcode sequence that is intended to represent a collection of > 1 molecule that originated from the same long molecule or sub-preparation within a library.  Usually (will we require this in the spec?) error-corrected and thus drawn from a known set of sequences.  This kind of barcode is exemplified by 10X's long molecule IDs, and needs to be placed in the BAM file to be useful.
3. UX - a Unique Molecular ID (UMI) that is intended to help differentiate between sequenced molecules that would otherwise appear to be duplicates of one another.  An example of this use case is Agilent's HaloPlex, where because many inserts share start/end positions a random sequence is added to the adapters to differentiate otherwise same-seeming inserts.

One difference that should be noted is that #1 *has* to be drawn from an expected set of barcodes to be useful, #2 is often drawn from a known set and to be most useful needs to be, #3 is usually drawn from a fully-degenerate random pool.

**Comment by nh13** [comment]
@tfenne that's what I would agree to.

**Comment by mattsooknah** [comment]
@tfenne's proposal sounds good to me too.

**Comment by yfarjoun** [comment]
@tfenne: What about RX/QX? Do we agree that it would include the raw sequence data from #2 and #3 barcodes (but not sample barcodes) separated with `-` (dash)?  The only problem is that while a dash is invalid as a sequence base it is a valid quality score. Should the qualities be concatenated without a delimiter, and assume the same structure as in RX? An alternative is to use a `~` (tilde) to separate the different barcodes for both sequence and quality. `~`  is the largest legal quality.

**Comment by tfenne** [comment]
@yfarjoun I wasn't trying to propose anything, more just clarify what was being discussed to see if I understood and could get on board.  I don't have a strong opinion one way or the other on RX/RQ, except to say that if 10X is going to drop those in their next release, is it worth defining them now?

**Comment by yfarjoun** [comment]
Well, 10x might drop them, but programs (for example
IlluminaBasecallsToSam) need to know where to put the data...

**Comment by nh13** [comment]
@yfarjoun I have no problems with many read groups (in the millions!).  

I would propose the following:
1. Sample Barcode: optional read-level tag (`BC`) to store the *observed* (sequenced) barcoded bases, and read-group tag (`BC`) to store the *assigned* barcode bases.
2. Molecular Index (MID): optional read-level tag (`RX`) to store the *observed* (sequenced) MID bases, and read-group tag (`RX`) to store the *assigned* MID bases.
3. Read Index (RID): optional read-level tag (`UX`) to store the *observed* RID bases.  Given these are truly random, I don't see a need for an equivalent tag for *assigned* RID bases.

The motivation is that I really don't want to have to store `RX` for every record, when it can be more easily put in a read group.  The files will be much smaller.  Same thing for `BC`.

**Comment by yfarjoun** [comment]
@nh13, with the @RG idea one would have to start collating information across readgroups if one is to find sample*lane level metrics...that sounds a bit onerous...

**Comment by nh13** [comment]
@ablewhiskey: this makes me very conflicted.  I want @yfarjoun to be able to support 10x data in Picard, but given the rapid evolution of how 10x is representing their data, I would caution us to add things to the SAM spec will not be used long term.  See for example `FZ` which was replaced by `ZM` for Ion Torrent data.  Perhaps we wait a little longer until the data format has matured?

@yfarjoun look at `MultiLevelCollector` closely, for example `ReadGroupCollector` keys off of the `platformUnit` and I believe will correctly handle multiple read groups with the same sample, library, and platform unit.

**Comment by mattsooknah** [comment]
Hmm yeah, perhaps we should wait. Having out-of-spec tags in the wild (for now) seems better than adding tags to the spec, and then deprecating / removing them.

However, perhaps we should still clarify ```BC``` to mean sample barcode now, to avoid issues down the road.

**Comment by yfarjoun** [comment]
I still think that the RX/QX tags could be added to the spec since the
upfront software the extracts them from the sequencer needs to know where
to place them.

Any objections?

**Comment by nh13** [comment]
I object to adding them to the spec, as 10x, who are the ones using RX/QX, are going to remove them in an imminent release.

**Comment by yfarjoun** [comment]
@nh13, forgetting 10x for a moment. I would like to extract raw molecular
sequence barcode reads(s) and put the data into the SamRecord in a tag.
What tags should I use? Should these be agreed upon here?

Even going back to 10x, I imagine that "internally" they will still use
RX/QX but then remove these tags from the final BAM to lower confusion to
users. this means that advanced users will probably be able to run the
pipeline with this final step...what tag will they find the raw data in?

**Comment by nh13** [comment]
@yfarjoun my opinion is the same as above:
> I would propose the following:
1. Sample Barcode: optional read-level tag (`BC`) to store the *observed* (sequenced) barcoded bases, and read-group tag (`BC`) to store the *assigned* barcode bases.
2. Molecular Index (MID): optional read-level tag (`RX`) to store the *observed* (sequenced) MID bases, and read-group tag (`RX`) to store the *assigned* MID bases.
3. Read Index (RID): optional read-level tag (`UX`) to store the *observed* RID bases.  Given these are truly random, I don't see a need for an equivalent tag for *assigned* RID bases.

> The motivation is that I really don't want to have to store `RX` for every record, when it can be more easily put in a read group.  The files will be much smaller.  Same thing for `BC`.

**Comment by nh13** [comment]
Other folks should probably weigh-in as well @jmarshall @jkbonfield @tfenne.

**Comment by yfarjoun** [comment]
I don't like the idea of millions of readgroups for many of the reasons
mentioned by @ablewhiskey, for example GATK's BQSR creates a per-Readgroup
model, and I'm not sure if it looks at the tags like picard's multi-level
collector. Other programs will probably be similarly not ready for this
change. That said, this proposal does not stop one from doing so.

Additionally, I think that primary programs like
IlluminaBasecallsToSam/FastQ do not need to know if a barcode is a
MolecularIndex or a ReadIndex. It's going to get the same treatment and so
splitting into two different tags seems like a needless complication. I'd
like to use only one tag for the observed molecular index, RX.

There will be  a program that looks at the extracted sequence and assignes
to a tag. that program can then remove the RX tag if needed to save space.
Also at that point millions of fake readgroups can be generated, so this
proposal is not blocking that idea.

**Comment by yfarjoun** [comment]
Please note that I've put in a PR that specifies parts of this issue. please comment there (#119) if you have an opinion.

**Comment by jkbonfield** [comment]
Any of the original people involved in this discussion, we welcome your views on how to resolve this long standing issue over here:

https://github.com/samtools/hts-specs/pull/200#issuecomment-305512849

**Comment by pmarks** [comment]
Pat from 10x here. Apologies for just noticing this thread.  If people can bear it we'd like to keep this conversation going a little longer:

* First off, our apologies for not being more proactive in requesting the standardization of the BX tag. We appreciate the work everyone here has done to keep the SAM spec in good shape. We'd reiterate that we've consistently documented and used BX for the linked-read data type since 2015: (https://web.archive.org/web/20150603064509/http://software.10xgenomics.com:80/docs/pipelines/output/bam)

* Existing uses of RX discussed in the thread (where there is data in the wild) are all 'traditional' UMIs where you're tagging a collection of reads that are PCR copies of the same 300-500bp library construct. 10x Linked-reads/BX has fundamentally different semantics, so we'd argue that these concepts should use different tags.

* At this point it's extremely difficult for us to justify switching off BX, now that we have substantial amount of data in SRA/ENA, IGV support (https://github.com/igvteam/igv/blob/a87260edb9eb53709f4467afa0232648eb4f4330/src/org/broad/igv/sam/AlignmentTrack.java#L2447), and an ecosystem of tools that expect BX tags (e.g. https://github.com/walaj/bxtools, https://github.com/abishara/athena_meta, https://github.com/bcgsc/arcs, https://github.com/bcgsc/tigmint, https://github.com/grocsvs/grocsvs)

* **We'd like to float a new proposal**: Define RX as a 'traditional' UMI (as currently decided), but define BX to denote a collection of short reads generated from an a limiting dilution subsample of long molecules from the sample genome. We can stop using RX in our BAM file fairly easily, because we've always told our users to focus on BX, and one tool for BAM->FASTQ conversion we have that does consume the RX tag is configured with a custom header that we can update.

Thoughts on this amended proposal?

**Comment by serine** [comment]
@yfarjoun was catching up on this discussion about UMI and how to add/represent them in a BAM file.

Looking at latest [SAMtags.pdf](https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf) specs 

These two tags are little confusing to me **RX** and **MI** and what had happened to **BX** tag?

```
RX:Z:sequence+ Sequence bases from the unique molecular identifier. These could be either corrected or
uncorrected. Unlike MI, the value may be non-unique in the file. Should be comprised of a sequence of
bases. In the case of multiple unique molecular identifiers (e.g., one on each end of the template) the
recommended implementation concatenates all the barcodes with a hyphen (‘-’) between the different
barcodes.
If the bases represent corrected bases, the original sequence can be stored in OX (similar to OQ storing
the original qualities of bases.)
 ```

and 

```
MI:Z:str Molecular Identifier. A unique ID within the SAM file for the source molecule from which this
read is derived. All reads with the same MI tag represent the group of reads derived from the same
source molecule.
```

The paragraph in **RX** seem to undermined UMI's by _ Unlike MI, the value may be non-unique in the file_  How do you know to which **MI** to assign  some UMI if it isn't unique? For example if you have **MI:Z:ID1   RX:Z:AATTCCGG** and **MI:Z:ID2   TX:ZAATTCCGG** How does assignment of **AATTCCGG** gets decided to whether assign to **ID1** or **ID2**? 

Also [this link from 10x genomics](https://support.10xgenomics.com/genome-exome/software/pipelines/latest/output/bam) advises not to sue **RX** tag in you analysis, rather use **BX** however in the specs this is ambiguous _These could be either corrected or uncorrected_ .

For me this is all about MarkingDuplicates, ideally with `picard`. From docs 

```
BARCODE_TAG (String) | Barcode SAM tag (ex. BC for 10X Genomics) Default value: null.
READ_ONE_BARCODE_TAG (String) | Read one barcode SAM tag (ex. BX for 10X Genomics) Default value: null.
READ_TWO_BARCODE_TAG (String) | Read two barcode SAM tag (ex. BX for 10X Genomics) Default value: null.
```
 
So for single end data and using new specs (provided BAM files follow the specs) I'd use

```
READ_ONE_BARCODE_TAG=RX
```
to deduplicate taking advantage of UMI's?

Just to finish off, why have **MI** tag?

p.s looks like part of my question was addressed [in the comment above](https://github.com/samtools/hts-specs/issues/109#issuecomment-158190238) so give that **MI** was set right some how, one can simply drop **RX** or **BX** and simply use **MI** to deduplicate? So in that case

 ```
READ_ON_BARCODE_TAG=MI
``` 
?

Many thanks

**Comment by nh13** [comment]
@serine we can use both the value in the `RX` tag and the template coordinates (mapping coordinates) to assign the `MI` tag.  For some example tools that are not 10x, see [UMI-tools](https://github.com/CGATOxford/UMI-tools) or[ fgbio's GroupReadsByUmi](http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html).  This is common to a lot of various single-UMI and duplex-sequencing-UMI kits commercially available, where we either use the UMIs to improve duplicate marking (i.e. increase effective depth) or go as far as producing consensus sequences from the reads that observe the same source molecule (have the same `MI`).  Thus, two reads can have the same `RX` but be assigned to different `MI`s.
