### ISSUE TITLE
sam Pnext and Rnext question?

### ISSUE THREAD

**Issue by kongdeju** [samtools/hts-specs#110]
What does the "Pnext"  refers to  if the read is paired and also has secondary alignment ?
The Pnext here refers to the next pair  or next seqment ?

**Comment by jkbonfield** [comment]
Officially PNEXT and RNEXT always refer to the ***primary*** alignment for the next segment, even if this segment is a secondary alignment.  So that's how it should (and normally does?) work. 

There are cases where this is obviously the correct thing to do (one end having primary and secondary alignments while the other end only has one single unambiguous primary alignment), but other cases where it seems illogical.  E.g. the entire template can map as a self consistent read-pair in two locations, in which case I would want the pnext/rnext for the secondary template-pair to point to each other rather than to their primary cousins. 

Personally I'd like the meaning of pnext/rnext/tlen to be up to the aligner to do what it thinks is the "right thing".   That's a bit woolly, but so are all the ways these fields can be used.

**Comment by kongdeju** [comment]
@jkbonfield  Thanks for your specification.
