### ISSUE TITLE
Data type of qual in BAM

### ISSUE THREAD

**Issue by karel-brinda** [samtools/hts-specs#128]
Data type of ``qual`` in the BAM specification should probably be ``uint8_t``, not ``char``. Since ``char`` can be either signed or an unsigned (see below), it is not clear if ``qual`` is really of an unsigned type, or not.

Rationale for  American National Standard for Information Systems - Programming Language - C:

> Three types of char are specified: signed, plain, and unsigned. A plain char may be represented as either signed or unsigned, depending upon the implementation, as in prior practice. The type signed char was introduced to make available a one-byte signed integer type on those systems which implement plain char as unsigned. For reasons of symmetry, the keyword signed is allowed as part of the type name of other integral types.

**Comment by mp15** [comment]
Agreed, especially given what happens when you try and index into an array with it and it casually gets sign extended. Perhaps we should expand this issue to cover all uses of char in the BAM struct?

**Comment by tfenne** [comment]
The use of unsigned types causes a lot of pain in the Java (and possibly other) implementations of the specification, because of the lack of unsigned types in that language - it generally means promoting values to the next integer type and consuming more memory, and then implementing extra checks when setting/writing those values that they are not out of range of the unsigned type.

Where possible it would be good to avoid unsigned types, even when the values in question don't support negative values.  In this case, a signed 8-bit number integer is plenty of room to store a phred scaled quality score.

**Comment by karel-brinda** [comment]
Btw. here is an example what could happen on a platform, where ``char`` is signed (note that ``0xff`` is reserved for missing data quality):
```c
#include <stdio.h>

int main(){
	signed char a=0xff;
	printf("%d\n",(int)a);
	printf("%s\n",(a==0xff) ? "true" : "false"); 
}
```

Output on my computer:
```
-1
false
```

**Comment by jmarshall** [comment]
The range of the characters in SAM's QUAL field is `[!-~]`, which corresponds (after subtracting 33) to `[0,93]`.  So the actual range of the entries in BAM's `qual` array is `{0, …, 93, '\xFF'}`.  It is immaterial for the specification whether this is signed or unsigned — the quality values 0,…,93 fit either way, and the numeric value of the absent code is irrelevant, you just have to be able to recognise the bit pattern 0xFF.

I'm not terribly excited about the use of C type names like `char` in the spec, but as a way of saying "one octet of (for Java's benefit) unspecified signedness" it's accurate and IMHO fairly clear.

Implementations in languages like C are free to implement this with an unsigned type if they wish, as due to the restricted range no-one will be able to tell the difference.

**Comment by mp15** [comment]
What bugs me is the inconsistancy that we are using uint32_t, uint16_t but for 8 bits we for some reason switch to char. A tightening up of this does not make any actual real world difference to Java developers because the type is the same size and as @jmarshall points out range restricted but would reduce the possibility of stupid sign extension mistakes on other platforms.

**Comment by jkbonfield** [comment]
On Thu, Feb 04, 2016 at 02:27:34AM -0800, Tim Fennell wrote:
> The use of unsigned types causes a lot of pain in the Java (and possibly other) implementations of the specification, because of the lack of unsigned types in that language - it generally means promoting values to the next integer type and consuming more memory, and then implementing extra checks when setting/writing those values that they are not out of range of the unsigned type.

We already use 255 for the unknown qual marker, so we can't simply say
0-127 is sufficient.

Also we have two issues here - implementation vs specification.  The
specification should explicitly state that it is unsigned, as it is.
The Java implementation (or samtools of coruse) should feel free to
implement it as signed and check for -1 instead of 255.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
