### ISSUE TITLE
CRAM File Definition version numbers

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#141]
§5 of CRAMv2.1 and §6 of CRAMv3 each say

Data type | Name | Value
--- | --- | ---
byte[4] | format magic number | CRAM (0x43 0x52 0x41 0x4d)
unsigned byte | major format number | **2 (0x2)**
unsigned byte | minor format number | **0 (0x0)**
byte[20] | file id | CRAM file identifier (e.g. file name or SHA1 checksum)

Presumably the major/minor numbers should be 2/1 and 3/0 respectively.

It would also be good if both specifications (or at least the most recent one) also gave a range of what major/minor numbers have ever been valid and therefore may be seen in the field.

So e.g. major ∊ { 1, 2, 3 }, minor ∊ { 0, 1} or similar.

**Comment by jkbonfield** [comment]
Agreed.

Vadim, is this something sufficiently trivial you'd be happy for one of us just to update the specification without making a pull request?  It's just a documentation error correction rather than a change to the behaviour of any tools implementing the specification.

If so I can make the change.

**Comment by vadimzalunin** [comment]
@jkbonfield sure, please update the specs.

**Comment by jkbonfield** [comment]
I want to add a brief history.  Something like:

* 1.0  The first official public release.
* 2.0  First release supported by both Java and C tool-chain; tidied up implementation vs specification differences in 1.0.
* 2.1  Gained end of file markers, compatible with 2.0.
* 3.0  Additional compression methods; checksums.

Is this an appropriate one-line summary?  I don't want to enumerate every change, partly because I cannot recall them all and it was only from 2.1 onwards that the specification was in git and from then on git logs themselves cover every tiny nuance.  Also my recollection of 1.0 is that the files produced by Cramtools 1.0 weren't using the same on-disk format as the specification for 1.0; this is mainly what we tidied up in 2.0, but I don't know how to phrase that.  Is my summary appropriate for inclusion the specification?

**Comment by jmarshall** [comment]
:+1: I think such an overview of the significant changes leading to version number bumps is useful and appropriate.  I have a draft of something similar for SAM, where there is even more git history to sift through…
