### ISSUE TITLE
Clarify 'first segment in template'

### ISSUE THREAD

**Issue by SoapZA** [samtools/hts-specs#169]
Dear maintainers,
would it be possible to clarify that **first in pair**, does not actually imply the read with the lowest **POS**, instead, it implies the read coming from **R1 / forward sequencing** in a paired-end experiment? Given the current spec, this is not at all obvious to me.

**Comment by jmarshall** [comment]
Probably _“For sequencing data, reads are indexed by the order in which they are sequenced”_ in §1.2 (the glossary) is supposed to imply this, but you are right that this is unclear and needs to be reiterated in the section on flags.

Note that the current spec talks about first/last of multiple segments in templates rather than first/second in pairs.

**Comment by SoapZA** [comment]
@jmarshall Ok, reading over it a second time seems to imply it, but this definitely needs to reconnect to the flags, preferably explicitly stating that first segment in template **is not** the segment with the left-most mapped base.

**Comment by jmarshall** [comment]
Hopefully this change clarifies it sufficiently.  I haven't explicitly mentioned that this is not "the segment with the left-most mapped base" or similar as a full description accounting for the ends being mapped to different chromosomes etc seems like it would be more confusing, not less; but YMMV.

**Comment by SoapZA** [comment]
@jmarshall Thanks, the example with R1 and R2 made it clear enough.
