### ISSUE TITLE
Value of NM tag when ambiguous bases are involved

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#177]
The definition of the NM tag is 
  > Edit distance to the reference, including ambiguous bases but excluding clipping.

The Tags file doesn't edify much more. It find it unclear, in particular, what does "including ambiguous codes" mean? 

I can understand it in two different ways:
A:
> "taking into account that an ambiguous code is always an edit distance away from anything" 

B: 
>"if a read base matches the pattern of the reference the edit distance is 0, else 1"

Here's a table of examples with the two possible interpretations:
 
\#  | Read | Ref | NM (A) | NM (B) | comments
----|----|----|----|----|---
1| A | A | 0| 0| clearly..
2| A| a | 0| 0| since bases as case-insensitive
3| A |G |1 | 1| clearly
4| A | g| 1 | 1 | base-insensitive
5| A| N | 1 | 0|
6| N| N | 1 | 0|
7 | N |A | 1| 1 | Since the read is less specific than the reference? not sure
8 | A| M |1 | 0 | M is A or C
9 | M| A | 1 | 1 | again, not sure
10 | M|R | 1 | 1| R is A or G...not sure here
10|M |M| 1 |0|

A discussion would be great, and when we reach an understanding, I'll be happy to submit a PR for the spec as well.

**Comment by colinhercus** [comment]
Hi Yossi,


Thanks for bringing this up. It would be great to have a clear definition.

Can you also consider case where read has a base with quality 2 Perr = 0.63
which is pretty much the equivalent to an N.

Kind Regards, Colin

**Comment by jkbonfield** [comment]
I totally agree with the need for a clear definition.

My personal preference is simple exact match only (case insensitive).  (Arguably N in seq vs N in reference is a corner case, as we know the base *is* incorrect, just unknown in both cases.  Samtools already has special code dealing with N.)  Otherwise it gets too complex.  What if we have R (AG) in SAM seq and V (ACG) in ref? Is that a match?  N technically matches everything, so is N in reference always a match to seq?  The list of cases is long, so best simply avoided.

I tried comparing samtools vs picard here, but alas couldn't get SetNmAndUqTags working.  Is there another way for it ito compute NM?   Samtools does appear to treat any textual mismatch (or an N N match) as a mismatch.  Conversely R in seq and R in ref is considered a match.  It also treats T vs U as a mismatch.

**Comment by yfarjoun** [comment]
I lean towards exact matches for non-ambiguous bases: R in both read and
ref isn't closer to a match than A in the read and R in the ref...it's
still right only 50% of the time.

Regarding base-quality, I think that NM should *not *take BQ into account
if osmeone wants to convert the bases of BQ=2 to N's that's up to them to
do, and then recalculate NM.

**Comment by tfenne** [comment]
I'm also in agreement that a clear definition in the spec would be great.  I think there are good cases for the non-obvious comparisons to go either way though.  There are times when it's useful to treat an `N` in reads as a mismatch against a reference base, and times when it is not.  In the context of the whole read I think there are really three pieces of useful information (which can be composed many different ways):

1. how much of the sequence positively matched the reference (i.e. A=A, C=C, etc.)
2. how much of the sequence positively mismatched the reference (i.e. A!=C)
3. how much of the match was uninformative (e.g. ref=N or read=N)

The problem is that we're tying to reduce a ternary classification (match, mismatch, no-answer) into a binary one.

Here's a good example of where one might prefer _not_ to count an `N` in the read vs. an `[ACGT]` in the reference as a mismatch.  VarDict and VarDictJava both use mapping quality and the NM tag to filter reads used in variant calling.  The thought being that you want reads that are confidently mapped (MQ) and don't show too much variation vs. the reference (NM).  If you had a 150bp read that mapped uniquely in the genome, had say 0-4 mismatches/indels but a a few Ns in the read due to some sequencer issue, counting the Ns as mismatches would inflate your NM tag, but intuitively _not_ reduce your confidence in the placement of the read or the accuracy of the other bases in the read.  You could argue that variant callers should re-calculate NM or a similar metric themselves, but in reality at least one popular caller users the tags directly.

@yfarjoun: If the reference is 'M' and a read is 'A' (or vice versa), I'd argue that's not wrong half the time, it's stating the ambiguity.  If you ask me who did something and I say, I'm not sure but it was either you or John - so long as it was either you or John, I'm right all the time, I'm just under-specific.

**Comment by lh3** [comment]
@yfarjoun has talked to me about this. I mildly favor (A), but can go with (B) or other definitions. The definition of NM has a very minor effect in real data analysis. I am ok as long as there is a consensus and the definition is unambiguous.

**Comment by yfarjoun** [comment]
Oh look! we talked about this already  a year ago! 

https://github.com/samtools/samtools/issues/717

Too bad it got dropped...

**Comment by jkbonfield** [comment]
Bumping this again as I've been recently patching htslib CRAM support to try and avoid some of the confusion.

My preference is option A above - make any non ACGT bump NM by 1 regardless, which essentially is treating NM as a potential error count ("potential" as it could be a mutation).  This permits NM to be used as a QC check to consider reads with high difference counts as a proxy for possible high sequencing error rate.

**Comment by jmarshall** [comment]
Aside from calmd, the other instructive original implementation of NM calculation would be in BWA. However for various reasons it's not very interesting, just using a very simple calculation.

I don't have strong opinions on this, so happy to go with the consensus (A). How does this align with the existing implementations?

**Comment by jkbonfield** [comment]
A summary of calculations so far:

### samtools calmd ###
Any vs N is mismatch, including N vs N.
All ambiguous bases are like N, so R vs R is also NM+1, as is A or G vs R.
This is symmetrical, so R in sequence vs A/G in ref is also mismatch.

### htslib CRAM ###
As per samtools calmd.

### picard SetNmMdAndUqTags ###
Base vs N is mismatch, but N vs N is match.
Base vs R and R vs base are both mismatch, regardless of base compatibility.
Ie identical to samtools calmd *except* for the N v N case.

### cramtools --calculate-nm-tag ###
Ad per picard above except ambig (seq) vs N (ref) isn't a mismatch.  Likely it turns all non-ACGT to N before doing the comparison.

### io_lib CRAM ###
Also as per picard above. (This differs to htslib in N vs N, but a change was made to htslib which apparently didn't appear in io_lib.)

### bwa ###
Num mismatches + num gap, where mismatch is any query != ref and num_gap is sum of cigar D lengths.  Ref is only 2-bit though, so in my file N (seq) vs N (ref) was mismatch and G vs N was match. N seq vs anything in ref was mismatch though.   This is simply incorrect and not going to match any definition, but *mostly* we can say any seq vs N in ref is mismatch.

Similarly the 2-bit encoding of ref makes ambiguity codes count wrong.  R (seq) vs R (ref) is mismatch, as is A, G and T vs R, but C vs R is counted as a match, presumably because that's what the reference became at that point. (Why C here and G earlier?  Who knows!)  This also causes MD tags to change ambiguity codes in reference to A,C,G,T bases.

At least it's case insensitive. :-)

### bowtie2 ###
Any seq base vs N ref is mismatch, including ambig vs N and N vs N.
Any seq base vs ambiguity in ref is mismatch, including R vs R.
Ambiguous bases vs non-ambiguous ref is sometimes a match (R seq vs A ref), but normally not (I assume ambig in seq becomes A).

### smalt ###
As htslib; all ambig / N are mismatch, including N v N.

So we have 2 sensible (ie "obvious") implementations: htsjdk (any N is mismatch, regardless where),  htslib (as htsjdk, but N v N as a special case mismatch); one mostly OK: cramtools (as htsjdk, but ambig vs N is also counted as matching); and the aligners are various degrees of bonkers.

**Comment by jkbonfield** [comment]
PR #308 added.
