### ISSUE TITLE
SAM encoding and C-style definitions

### ISSUE THREAD

**Issue by d-cameron** [samtools/hts-specs#197]
The SAM specifications do not define a file encoding. This is problematic as some "ASCII" encoding codepoints for punctuation that differ from "US-ASCII". This is extremely problematic as many of the Regexes use these characters as part of a regex interval.

Furthermore, the regex grammar used is not defined thus is ambiguous (see http://seqanswers.com/forums/showthread.php?p=205407#post205407 for context). Similarly, operators used in defining BAM headers are not explicitly defined.

Proposed resolution:

- Define the file format as "US-ASCII"
- Add introductory text that states that
   - All regexes are POSIX basic regular expressions
   - code and pseudo-code in the document should be interpreted as C

**Comment by d-cameron** [comment]
Also, could a heading for predefined SAM tags be added to increased to prominence of the predefined tags document?

**Comment by jkbonfield** [comment]
Can you please clarify how these regular expressions are not POSIX regular expressions?  All I see is a basic character class with ranges, which has been a core part of regexp since inception and is already POSIX.  There is an assumption on ASCII rather than EBDIC as it specifies character classes with an assumption on collation order.   

Are you proposing use of the more complex [[:alnum:]] POSIX extensions over the original REs without any automatic collation order assumptions?  If so I disagree as these aren't really an improvement over a basic ASCII table.  Eg the RNAME regex would change from ```\*|[!-()+-<>-~]``` to (I think) ```\*[-!"#$%&'()+,./:;<>?@[:alnum:][]\^_`{}|~]```, assuming those quotes and backslashes don't need escaping in any way.   Basically posix there isn't any benefit to posix character classes here.  There is one slightly bizarre thing in the original document with ```!-()``` which could simply be ```!-)```.

I also don't understand the distinction between ASCII and US-ASCII and online sources seem to imply they're synonymous.  Certainly I cannot imagine the collation orders differing, which ultimately is what matters.

However you are correct that it should state the file encoding somewhere for completeness.

**Comment by d-cameron** [comment]
>Are you proposing use of the more complex [[:alnum:]] POSIX extensions over the original REs without any automatic collation order assumptions?

I'm advocating for a single sentence to be added somewhere in the document that states what sort of regular expressions they are as they could be interpreted as POSIX extended, PCRE, or some other sort of regular expression.

> I also don't understand the distinction between ASCII and US-ASCII and online sources seem to imply they're synonymous. Certainly I cannot imagine the collation orders differing, which ultimately is what matters.

Since punctuation code points are used in the Regexes, the 'flavour' of ASCII matter as some "ASCII extensions" replaced have these characters at different code points. It's not so much the collation order, but the unambiguous interpretation of code points used in the regex. Although ASCII is technically correct, US-ASCII is the is IANA preferred term.

**Comment by jkbonfield** [comment]
I see what you mean regarding regular expressions.  To be formal we're using the most basic elements from POSIX "extended" regular expressions.  PCRE is an irrelevance here as the features we use are the same in both.

Punctuation defined in the regexps though is entirely 7-bit ascii so deliberately tying it to "US ASCII" works, but in all encodings bar EBDIC ```!-~``` is still 7-bit and means the same thing (every printable character) so while it's helpful to tie it down it is still not a valid reason to ignore it (as was the case in the linked thread)!   The regexp is messy, but easier to interpret than a piece of woolly English text - the above phrasing may be interpreted to include the Spanish upside-down question mark for example.

Sadly however this ship has, alas, already sailed!  Data in the wild already exists using UTF8 for header descriptions and sample names.  This is strictly against the spec, but alas real data sometimes arrives with UTF8 database fields prior to generation of SAM/BAM.  (Arguably this is a fault of input validation in the original sequencing submissions, but that's another issue entirely and I very much doubt we're the only ones with this problem.)

So I think ideally we'd want to state all fields are 7-bit US-ASCII with specific exceptions for UTF8 in some fields. @dkj has more experience of this in the wild and should be able to report the fields where we've seen UTF8 symbols coming through the pipelines.

**Comment by d-cameron** [comment]
Is there any interest in a SAM "strict" sub-specification? It'd be really nice if, as tools developer, we should assume that the input SAM file actually made sense. I'm imagining a formalisation and expansion of section 2 of the specifications with a bunch of additional sanity checks. Eg: paired reads are actually paired, mate information is correct, secondary/supp tags are written in a non-legacy manner, sort order matches header, alignments should not overrun contig bounds, all regexes satisfied, and so on. An formal definition of a sensical SAM file with validators (e.g. Picard ValidateSam STRICT=true) would free tools from having to handle a different flavour of SAM for each aligner they want to be compatible with.

**Comment by yfarjoun** [comment]
I think that it would be very nice to have. There's even one reference
implementation, in case you want to write this section :-)

**Comment by jkbonfield** [comment]
As I see it now there are two classes of error we handle.

1) Syntax errors.  These are the ones where people flagrantly break the specification, such as putting spaces in chromosome names or UTF8 characters in headers.  We need to review these to work out why the errors occur, but generally we don't need to change too much here as the specification is already (mostly) clear on the syntax.

2) Semantic errors.  These are valid SAM files, but have inconsistencies in their meaning.  There are a huge raft of these errors that crop up all over the place in real data.  We even have tools designed specifically to fix them ("fixmates" for example) because they're so prevalent due to long-standing aligner bugs.   The specification was even relaxed at some point to work around these bugs!  It's a worthy goal to tighten these up again, but it needs to be done in conjunction with a fixer tool too or it'll just be a case of "spec says this" + "everyone else does this".  (See TLEN for example where there has been flat out refusal to adhere to the spec but also little interest in changing the spec either.)

Note you also have to consider the sub-set case.  We can validly claim we are a paired read without the other read being present at all due to a range-query.

**Comment by jkbonfield** [comment]
As noted in maintainer conference call - we need to also specify locale somewhere.  It's not an issue for SAM as floating point numbers are explicitly defined via a regexp, but for consistency with other specs (eg VCF has heavy use of floats) we should add the same locale to all.   I'd recommend "C".
