### ISSUE TITLE
Representing custom sort and group orderings in SAM/BAM

### ISSUE THREAD

**Issue by tfenne** [samtools/hts-specs#204]
I would really like a way to represent custom orderings in SAM/BAM/etc.  There are a number of tools, across multiple organizations and code bases that emit BAM files that have been sorted into specific orderings that are not representable in a standard way in the current header.

The only solution(s) currently are to add additional tags to the header to represent things, e.g.:
`@HD  SO=unsorted so=duplicate-ordered`.  I think this is a general enough issue that it would be worthwhile standardizing how to represent this information.  Though the orderings themselves are often esoteric enough that standardizing those would likely be a bad idea.  For example, I have one custom ordering I use that sorts all records by "the 5' unclipped position of the primary record for the read within the pair that is earlier on the genome"!

I can think of a few ways of specifying this, that range from total backwards compatible, to ones that are not backwards compatible (though would be easy to adjust to).  I'd like to gather feedback here, and if there is support, I will create a PR.

I'll also note, that the solutions I'm proposing could also be used to provide a nice solution to the samtools vs. Picard queryname sorting issue that has existed forever.

### Option 1: Totally Backwards Compatible
Add a new standard tag to the header that specifies "sub-sort-order", where the tag is standard but the values are unconstrained.  This would allow things like (using `SS` as the new tag for the examples):

```
@HD  SO:queryname  SS:lexical
@HD  SO:queryname  SS:numeric-lexical
@HD  SO:unsorted   SS:duplicate-order
```

Existing tools could largely ignore the `SS` tag in the header, and custom orderings could be defined with SO:unsorted and custom values for `SS`.  This could give rise to odd situations though when an existing tool resorts a BAM and doesn't know to remove/update the `SS` tag, giving rise to incorrectly labeling.

I'm also not super-keen on breaking the information across two fields personally.

### Option 2: Semi-backwards compatible
Allow "sub-typing" of sort orders.  Pick a delimiter character and then a sort order may be composed of a "major" and _optionally_ "minor" ordering, e.g.:

```
@HD  SO:queryname:lexical
@HD  SO:queryname:numeric-lexical
@HD  SO:unsorted:duplicate-order
```

Under this model `SO:queryname` would still be totally valid, so all existing files would be forward-compatible.  But tools would need to be updated to parse the slightly more complicated SO format.  The upside is that tools that resort BAMs, even before being updated, would not generate incorrect information.

### Option 3: Only fowards-compatible

As option 1 or option 2, but introduce a new sort order `custom`, instead of using sub-orderings on `unsorted`.  This would obviously be much clearer moving forward, but would introduce a new sort order that older tools might not be able to handle.

**Comment by magicDGS** [comment]
I like this idea because I'm struggling on how to use Picard/samtools queryname sorted files in a proper way. Several things about the different options:

* Option 3 will break compatibility for sure in case that unknown sort orders are not correctly handled in some piece of code. In addition, custom will allow to create sort orders in the wild difficult to handle by general purpose libraries like HTSJDK.
* I think that Option 2 is a nice one, but I guess that it is a breaking change that does not add anything to software that is already agnostic about the "queryname" type, and adds complexity to the parsing. It is even more complicated for "unsorted", which it can have now unlimited names.
* Option 1 makes more sense for me, because it is completely backwards compatible and it will simplify things. For instance, by parsing `SO:queryname` alone, this allows to determine that the read pairs are together and that is the only thing that should be important for some programs. If the requirements are more specific, parsing the `SS` tag will allow extra validation. It is also cool to be able to specify the rules used in `coordinate` sorted files.

I believe that Option one is the more flexible one and the one generating less headaches to developers. But that's just a biologist opinion 😀

**Comment by colinhercus** [comment]
While you're at it could we have a sort order for "Grouped by Readname"
most aligners output this and some downstream programs expect it.

**Comment by magicDGS** [comment]
@colinhercus, I think that `queryname` sort order is what you call "Grouped by Readname". The only problem currently is that the read names could be ordered in different ways dependeding on the implementation, and this is what will be solved with one of this options...

**Comment by d-cameron** [comment]
Under the proposed changed, "Grouped by Readname" would be something like  `@HD  SO:unsorted  SS:groupedbyqueryname`.

This different to an implementation-dependent queryname sort order since it is a considerably more relaxed constraint that an actual ordering.

I'm yet to encounter an actual use for queryname sort order that was not actually a requirement of "group by Readname". I suspect this is why the sort order issue with Picard and samtools is still around: programs that need queryname sorted only actually care about readname grouping.

If we're changing sorting, I'm strongly in favour of some sort of "Grouped by Readname" "sort order" being included it is so useful in so many contexts. It could even be shoehorned into the current model in a fairly backwards compatible manner by calling it something like `@HD  SO:queryname  SS:unsorted`.

**Comment by nh13** [comment]
@magicDGS grouping by query name implies no order between the groups, just that reads with the same name are grouped. Subtle but important.

**Comment by colinhercus** [comment]
My vote for @HD SO:queryname SS:unsorted

**Comment by jkbonfield** [comment]
@colinhercus Group by read name is precisely what the GO tag is for.  It permits us to say it is unsorted, by query-name collated.  It absolutely should not be stating SO:queryname when it is *not* sorted by query name as this is simply incorrect.

@tfenne Regarding the proposal, option 1 is my favoured and it can be tweaked to be *mostly* detectable for tools that don't update the field by adding in option 2.  Eg say we have a name sorted file from picard:

```
@HD SO:queryname SS:queryname:lexical
```

We sort it with an old tool and get:

```
@HD SO:coordinate SS:queryname:lexical
```

At this point the prefix of SS doesn't match SO so we can tell that it's not up to date.  Of course if it gets sorted back to queryname again by an old samtools then it'll end up with

```
@HD SO:queryname SS:queryname:lexical
```

and still be incorrect as the sub-sort isn't correct any more.  (Assuming we're shoehorning in the different name collation order between the tools into sub-sort, which isn't technically a sub-sort but feels like the only place we can put it. although personally I'd be in favour of simply removing that cleverness from samtools.)

So it's far from perfect, but has partial protection.  If we have tools that sanitise the headers and remove any SS that doesn't match the SO field then we can tidy up mismatched tags before they get transformed back to potentially undetectable problems.

Option 2 would break any existing implementation that simply checked the valid strings mentioned in the specification, which includes my CRAM implementation.  Most of the rest of samtools appears to never check this field or do so via highly questionable routes (eg ```p = strstr(header->text, "\tSO:coordinate");```) due to the sad lack of any header API!  Many implementations have better APIs with stricter checking though.

Option 3 is workable I guess in as far as it's immediately obvious that this is an extension, but it suffers some of the same compatibility issues as option 2.   Perhaps tools would just treat ```custom``` the same as ```unknown``` though so maybe it's less of an issue?

**Comment by tfenne** [comment]
@jkbonfield I like you're suggestion for a modified option 1.  That strikes a nice balance between backwards compatibility and being able to detect most misuses.  I'll wait a few more days and if nobody shows up with a strong opposition I'll put together a PR that codifies that option.

Regarding the lexical vs. numero-lexical (I don't even know what to call it!), I sort of agree with you that it would be nice to do away with the second.  On the other hand, that is the effective ordering you get in illumina data (where it's sorted numerically by tile, x, y), and so it has the nice property that you can go straight to that sort order without having to actually sort the data.

Also, totally agree on the `GO` tag.  It's underutilized in general, but I do have tools that specify and/or require `GO:query` when the data is not `SO:queryname`.  @colinhercus does that not work in your case, or were you unaware of the `GO` header attribute (which wouldn't be surprising since almost noone uses it!)?

**Comment by colinhercus** [comment]
My bad. I hadn't seen the GO tag. I'll start using it.

**Comment by tfenne** [comment]
To all still interested, #221 is a first pass at a PR to add this to the spec.
