### ISSUE TITLE
htsget: add specificaton version to api/response

### ISSUE THREAD

**Issue by AlexanderSenf** [samtools/hts-specs#207]
Now that there are more than one htsget (Streaming API) protocol specifications it will be possible that there will be live servers adhering to different spec versions. It would be helpful if the spec version would be available from the API itself; either as a request parameter, or as an extra field in the JSON response; or by specific request.

**Comment by jmarshall** [comment]
[@mlin: There's already a `[transfer-protocol]` label for this.  Perhaps you should merge the labels.]

**Comment by mlin** [comment]
@jmarshall thanks for pointing that out!

**Comment by jmarshall** [comment]
I think the only thing that's changed between the two extant versions that could cause confusion for clients is the syntax of the error response JSON (`{"error": {"type": "foo", "message": "bar"}}` vs. `{"error": "foo", "message": "bar"}`).  So as yet there's probably not too much of a problem.

At the moment we only have one request in total (`…/reads/<id>`), so adding a specific request for versioning seems somewhat overkill.

[More conversation exists on the mailing list.]

**Comment by daviesrob** [comment]
I'd still like to see something in the response to identify the protocol and version.  Currently htslib looks for the string `{"` in order to identify an htsget reply (as opposed to cram or html or jpeg or anything else the server may throw back at it), which hardly seems robust.  In particular, it would be nice to be able to reliably tell htsget JSON responses from any other form of JSON that arrives.

**Comment by jmarshall** [comment]
Indeed, there's at least a couple of different facets here:

1. a way for clients to ask for a particular version of e.g. `/reads/` response that they would like to get back
2. a way to identify that some JSON is indeed of a particular response version
3. an identification of the server's supported version (whatever that means beyond the first two points; or is it just the `Server` response header?)

@daviesrob's is (2), which could just be something like `{…"htsget": "0.2"…}` in the response.

:+1: sure, why not, although it's not much good as a magic number if we keep having `{…}` as the top level of our JSON responses — as you surely can't force a particular ordering on people's JSON libraries in general.  So we might need to go to an artificial `[ "htsget-0.2", {…} ]` style of response JSON.

**Comment by jmarshall** [comment]
Re (2), we could of course trigger on a response `Content-Type` like `application/vnd.ga4gh.htsget.v1+json` or so.  However it's non-trivial to get at the content-type in some clients (e.g. htslib, which unifies http streams and raw files etc, so can't easily access HTTP headers), so there is something to be gained from having the JSON be self-identifying too.

**Comment by jeromekelleher** [comment]
Here is my take following the call:

1. Client MAY provide a HTTP ``Accept`` header to specify the version of htsget that they require. This SHOULD be in the form ``application/vnd.ga4gh.htsget.v1+json``. If not provided, the server is free to return whatever it wants.
2. Servers SHOULD send a ``Content-Type: application/vnd.ga4gh.htsget.v1+json`` header to the client.
3. Add a mandatory field ``"protocol": "application/vnd.ga4gh.htsget.v1+json" to the JSON response, so that clients that don't have access to HTTP internals can identify the protocol.

Does this sound about right?

**Comment by daviesrob** [comment]
Yes.

Ideally we would want the "protocol" string to appear fairly early in the response.  One (albeit rather hacky) way to do this without changing the protocol too much would be to force it in as the first object in the "urls" array.  That would ensure that it appeared in the first few hundred bytes of the response, something like this:

```json
{"format":"CRAM",
"md5":"8f780679f4f0e33fb76638025df0bf31",
"urls":[{"protocol":"application/vnd.ga4gh.htsget.v1+json"},
{"url":"ftp://ftp.sra.ebi.ac.uk/vol1/ERA640/ERA640027/cram/19220_1%231.cram"}]}
```

**Comment by jeromekelleher** [comment]
> Ideally we would want the "protocol" string to appear fairly early in the response. One (albeit rather hacky) way to do this without changing the protocol too much would be to force it in as the first object in the "urls" array. That would ensure that it appeared in the first few hundred bytes of the response, something like this:

I see the logic for this @daviesrob, but it seems a bit heavy-handed and also pretty brittle. JSON is explicitly defined as not having any order for fields, and there's nothing stopping servers adding in extra fields to the response. So, you could have a few K of data before the URLs array shows up. 

For htslib, we could imagine that it extends the existing rule to "if the first non-whitespace character is '{' buffer until the matching '}', and then pass to the JSON parser". This should be reasonably robust, and allow for other future JSON based protocols.

**Comment by daviesrob** [comment]
Buffering up the entire JSON stream would require a potentially unlimited amount of memory, so is not a good solution.

As the official format only defines three keys in the response, and two should be very short, we can cheat a bit by putting the format as the first entry in the urls list.  It is very ugly, though.

Looking the examples on http://www.json.org/example.html, they all have a single name/value pair at the top level.  Doing that might make for a good solution:
```json
{"htsget.v1" : {
  "format":"CRAM",
  "md5":"8f780679f4f0e33fb76638025df0bf31",
  "urls":[{"url":"ftp://ftp.sra.ebi.ac.uk/vol1/ERA640/ERA640027/cram/19220_1%231.cram"}]
  }
}
```

**Comment by jeromekelleher** [comment]
> Buffering up the entire JSON stream would require a potentially unlimited amount of memory, so is not a good solution.

I can't imagine a htsget response getting anywhere near large enough for this to matter, but I take your point. 

> Looking the examples on http://www.json.org/example.html, they all have a single name/value pair at the top level. Doing that might make for a good solution:
> 
> ```
> {"htsget.v1" : {
>  "format":"CRAM",
>  "md5":"8f780679f4f0e33fb76638025df0bf31",
>  "urls":[{"url":"ftp://ftp.sra.ebi.ac.uk/vol1/ERA640/ERA640027/cram/19220_1%231.cram"}]
>  }
> }
> ```

This is an elegant solution I think, much better than ``protocol=...``. What do others think of this?

**Comment by jmarshall** [comment]
It ensures the magic number is at the start just as the previously-suggested artificial top-level array does, but is more elegant and allows for overachiever servers to perhaps return

    { "htsget.v2" : { … }, "htsget.v1" : { … } }

not that that's likely to be a good idea in general.  So :+1:

It is a one-off significant change to our current main JSON responses that clients are parsing, so will require some synchronisation of server and client changes, so  is pretty much an inter-op flag day.  But that's probably okay while we're still embryonic.  (We already have a small change to the error JSON responses, but I'm guessing most clients are probably not actually parsing those.)

**Comment by tk2** [comment]
I like this too. Seems like a good solution. But the other server and client deverlopers should comment on any possible negative implications for their implementation.

**Comment by jmtcsngr** [comment]
Having the version as the name of the key looks strange to me. Will probably lead to problems even if it is the only element in the first level. For example finding the version will imply you somehow know the version you want to find. You have to query something like obj['htsget.v2'] instead of doing something more natural like obj[version] or obj[htsget][version]
`
{ "htsget": { "version": "1.0", data: ... } }
`
But since it looks more complex I would really like hear your opinions.
Should we consider semantic versioning?

**Comment by daviesrob** [comment]
@jmtcsngr This gets you back to the problem that you may have to read through a lot of data before finding out what the version number is.

I think it would be best if we defined that there must only be one key at the top level.  It would stop anyone from trying to slip the text of "war and peace" in before the data we actually want to read, and then complaining when things stop working because "the specification doesn't say you can't do that".

**Comment by jmarshall** [comment]
It's not unstrange but I think it is very effective.  If you're trying to find the version, you'll have the opportunity to do it by looking at the `Content-Type` you got back along with the JSON text.

Code parsing the JSON **does** know what version(s) of the format it wants to find.  It knows that it is capable of parsing v1, so it can ask for `htsget.v1`.

**Comment by jeromekelleher** [comment]
I agree with @jmarshall here. The client should know what version of the protocol to expect because (a) it has specifically asked for this version (using the ``Accept`` header) and (b) it has checked the ``Content-Type`` header to see what the version is. So, there's an argument to be made for leaving the version information out of the top-level item entirely:

```
{"htsget" : {
 "format":"CRAM",
 "md5":"8f780679f4f0e33fb76638025df0bf31",
 "urls":[{"url":"ftp://ftp.sra.ebi.ac.uk/vol1/ERA640/ERA640027/cram/19220_1%231.cram"}]
 }
}
```
I think it is useful to have the ``htsget`` key in there because it makes the JSON self-identifying. (I agree  with @daviesrob, we should require that this is the only key in the top level). Clients should use the HTTP ``Accept`` and ``Content-Type`` mechanisms for versioning.

**Comment by jmtcsngr** [comment]
@jeromekelleher  I remember @daviesrob mentioning they could parse a JSON from any source (file system). Not exclusive to http response. In that case I see the value of having a version in the JSON. Not sure if the JSON are meant to be long lived as they may contain auth tokens, but don't think there is anything specified rejecting the idea of saving your JSON and using them in the future.

**Comment by jeromekelleher** [comment]
> @jeromekelleher I remember @daviesrob mentioning they could parse a JSON from any source (file system). Not exclusive to http response. In that case I see the value of having a version in the JSON. Not sure if the JSON are meant to be long lived as they may contain auth tokens, but don't think there is anything specified rejecting the idea of saving your JSON and using them in the future.

Fair enough I guess, but I think it's a fair assumption that the ticket is not valid indefinitely. If this an assumption that we want to make, then we will have to make this explicit in the spec. Certainly I would have thought that this is a fairly hard constraint to impose on servers, and would undermine one of the central gains of using this protocol (namely, the freedom for servers to rearrange their internal structures as they see fit).

Is there a use-case of having a ticket stored in a file, beyond testing?

**Comment by daviesrob** [comment]
Mainly testing, although it can be useful to be able to jam segments of file together.  For example, it could be used to store cram headers detached from bodies (and so make replacing the header trivial).

I wouldn't expect server tickets to be valid for any length of time.  I think the main benefit to including the version in the JSON is that the parser can work out how to interpret the data without needing any form of side-channel.  Being able to use the token outside of an https transport is a bonus.

**Comment by jeromekelleher** [comment]
Thanks @daviesrob, that's helpful. I think it's fair to say that having ``htsget`` without the version information as the top-level key gets the vast majority of the benefit, in that it allows clients to identify the byte stream in broad-brush terms. I'm unconvinced that including the version within the actual JSON is of any real benefit, since (a) we don't believe that tickets are valid beyond the lifetime of the client/server transaction; and (b) the client will have to explicitly request a specific version that it understands using the ``Accept`` header. 

> Mainly testing, although it can be useful to be able to jam segments of file together. For example, it could be used to store cram headers detached from bodies (and so make replacing the header trivial).

I think we need to be careful of feature creep here. We are designing a client/server protocol here, not a file format or anything more general...

**Comment by daviesrob** [comment]
If you `Accept` more than one version then you have to work out what the server sent back.  Why faff around with getting the `Content-Type` out of the response when you could simply look to see what the one and only key of the top level JSON is?

**Comment by jeromekelleher** [comment]
> If you Accept more than one version then you have to work out what the server sent back. Why faff around with getting the Content-Type out of the response when you could simply look to see what the one and only key of the top level JSON is?

Well, I think it's better to say, why faff around with the top-level JSON when you could look at the  ``Content-Type``?  Ignoring the HTTP header information is a design choice that htslib has made; it's not inevitable, or, I would imagine, recommended.

**Comment by daviesrob** [comment]
Because getting the content type involves extra function calls, whereas the JSON key is directly available from the parser.

Of course, this is all fairly academic as we only have one version so far...

**Comment by jmarshall** [comment]
>  Ignoring the HTTP header information is a design choice that htslib has made; it's not inevitable, or, I would imagine, recommended.

It's actually an instance of Unix's fundamental [“Everything is a file”](https://en.wikipedia.org/wiki/Everything_is_a_file) design choice.  If everything is a file then there is no metadata and it is useful for the streams of bytes within files to be self-identifying.

While not inevitable, being an instance of one of Unix's defining features means IMHO that it's neither unrecommended nor an unheard-of design choice.

**Comment by jeromekelleher** [comment]
I'm a big fan of Unix and the success of the "everything is a file" abstraction within an OS @jmarshall, so I definitely sympathise with your point. However, I think you're pushing the metaphor too far here. One of the major points of this protocol in the first place is that **it's not a file**. Htsget is a network protocol, and clients should use the information provided through the standard HTTP headers. 

After thinking about it more, I'm pretty convinced that having a ``htsget.v1`` key in the JSON would cause more problems than it would solve. For one thing, it would make for ugly client code and likely lead to breakage after version updates. The easiest way to write a client would be
```python
ticket = json.loads(response)["htsget.v1"]
```
Clearly, this will break if the version number changes, even if the actual changes were compatible with the client. And what about minor version numbers? There's no point in putting the version in there if we don't put the minor version in as well. A client using the code about would then break, even though the actual changes to the protocol were (by definition, since it's a minor version change) compatible.

Adding the version number into the protocol key is a recipe for gratuitously breaking client code IMO.

**Comment by mlin** [comment]
Closing this issue in view of the completion of #226 and #230
