### ISSUE TITLE
fastq format?

### ISSUE THREAD

**Issue by colindaven** [samtools/hts-specs#208]
Does this group aim to cover FASTQ format as well ? There was a recent case where developers used 5 lines (4 descriptive, followed by a blank line) to describe each read.

The format is defined in a publication
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2847217/
and in the MAQ webpages
http://maq.sourceforge.net/fastq.shtml

Is it planned to maintain this spec here ?
Colin

**Comment by jkbonfield** [comment]
I don't believe it's in our remit,  although if the authors of that paper wished to maintain it then I'd be happy with them doing it here.   I think they published the paper out of frustration with no official spec existing, which was many years after fastq first came into existance.  (I don't suppose it was a desire to become a maintainer forever.)

**Comment by vadimzalunin** [comment]
Too many dialects imo. A generic specification to suit them all would be too simple and hardly useful. 
Inevitably fastq specs would have to follow major datasets available, like SRA fastq dumps etc. So effectively this would be a set of publisher/tool/platform specific specs, which are probably already described somewhere. 
Having said that, some recommendation may be useful, not sure if a consensus can be easily reached though. Stability in roundtrip tests for example would be a good goal.

**Comment by jmarshall** [comment]
That paper and the [Wikipedia page](https://en.wikipedia.org/wiki/FASTQ_format) are useful descriptions of the common parts of the various FASTQ dialects.  Extra conventions about subfields on the `@` line (such as the `1:Y:18:ATCACG` in Illumina FASTQ files) change over time and are described in various vendor documents and elsewhere (for `1:Y:18:ATCACG`, in the bcl2fastq documentation).

Rather than taking on FASTQ as an additional specification, this group might instead be inclined to recommend the use of unmapped-BAM or unmapped-CRAM in place of FASTQ.  Such files can do the job of a FASTQ file or a pair of paired-end FASTQ files, and have a well-defined way of adding tagged annotations that is more flexible than potentially-conflicting FASTQ `@` line conventions.

**Comment by peterjc** [comment]
As one of the authors of the FASTQ paper, I personally would also recommend we move away from FASTQ to using unmapped-BAM (or nowadays, unmapped-CRAM) - here's what I wrote about 6 years ago on this (matching John's comments above):

https://blastedbio.blogspot.co.uk/2011/10/fastq-must-die-long-live-sambam.html

(I'd have commented back in May, but never saw the issue till now by chance via a Google search)
