### ISSUE TITLE
Acceptable range of values for tags related to likelihood

### ISSUE THREAD

**Issue by Anishka0107** [samtools/hts-specs#244]
What is the acceptable range of values for tags like:
* CNQ
* CNL
* PL
* GL

**Comment by jmmut** [comment]
This is now explained in several places: section 2.1 in a general way, and in the definition of each one. as a summary, this is the general rule unless stated otherwise:
*P: p(x) -> [0, 1]
*L: log_10(p(x)) -> (-inf, 0]
*Q: phred scale. (-10 log_10(p(x))) -> [0, +inf)

note PL is defined as phred scale, so the name alone is not enough to know its range.
