### ISSUE TITLE
GP now in linear scale?

### ISSUE THREAD

**Issue by eyherabh** [samtools/hts-specs#260]
Contrary to VCF4.1 and VCF4.2, which specify GP in phred scale, VCF4.3 now specifies it in linear scale. Could you explain me the rationale behind this change and why wouldn't be better just to let anyone use any of the scales (phred, linear or log10) provided is indicated in the metadata? Thank you very much.

**Comment by lbergelson** [comment]
@eyherabh This seems to have changed because it was inconsistent with the labelling of other fields like GL/PL.  This now matches the scaling of GL, and the phred scaled version of this is PP.  PP was never added as a reserved tag, but it was adopted by GATK (I don't know if other tools emit it). We should probably add it as a reserved tag.
