### ISSUE TITLE
BGZF block conventions

### ISSUE THREAD

**Issue by betteridiot** [samtools/hts-specs#300]
One of the recent moves made was ensuring that if a read doesn't fit in the remainder of the current block it will start a new one. It is also well known that the last concatenated block contains the EOF marker. However, in some really low-level work, I found that the entirety of my BAM header was contained to the first BGZF block (e.g. BSIZE/ISIZE for first block was 1750 and 5271, respectively). The next block's BSIZE/ISIZE was 12682 and 65245, respectively as well.

Does this mean that there is a special convention regarding the header which attempts to enforce that the header is isolated from other data within its respective blocks?

**Comment by nh13** [comment]
I may be wrong, but I don't see anything in the BAM spec that requires this, but some tools will produce such data, for example Picard's `ReplaceSamHeader` tool, which uses the [`reheaderBamFile` method in htsjdk](https://github.com/samtools/htsjdk/blob/c9cab31191e786b6e1b6e83c4f47a39df726c1c6/src/main/java/htsjdk/samtools/BamFileIoUtils.java#L42).  Interestingly in the latter, the end of the header could be in a block with the first alignment/read/record, and so `reheaderBamFile` calls [this method](https://github.com/samtools/htsjdk/blob/c9cab31191e786b6e1b6e83c4f47a39df726c1c6/src/main/java/htsjdk/samtools/BamFileIoUtils.java#L86-L93) to writes the rest of the header into its own block. 

You can also see in htsjdk where it (writes the header to a BAM file and then flushes the block](https://github.com/samtools/htsjdk/blob/c9cab31191e786b6e1b6e83c4f47a39df726c1c6/src/main/java/htsjdk/samtools/BAMFileWriter.java#L208).

**Comment by jmarshall** [comment]
Several implementations began starting a new BGZF block after the headers and before reads that would otherwise be split across BGZF blocks as a result of [this June 2010 samtools-devel thread](https://sourceforge.net/p/samtools/mailman/samtools-devel/thread/AANLkTilCcBXyXt6zVgviEbKWuEhIxgzUV1noqGaZBcS0%40mail.gmail.com/#msg25496753) (starting with [this message](https://sourceforge.net/p/samtools/mailman/message/25496753/)).

The motivation for this is discussed in the thread — having the headers in a separate block was to facilitate tools like `ReplaceSamHeader`.

Nobody got around to adding these conventions to the spec, but I don't think there was any particular reason for not doing so.

**Comment by jkbonfield** [comment]
BAM is long enough in the tooth that making these requirements probably won't be possible, however there is room in the spec for guidance and best practices.  It would make sense to add this somewhere appropriate.

Practically however that means you cannot rely on them if you accept data from third parties, unless you know their tool chain complies.  As long as you check all errors, it's probably common place enough now that you can simply fail on "non-confirming" files and wait and see if they ever crop up!

Note - if you ever deal with long read data, starting a new block when the current one isn't large enough to fit your next read is not the same as every block starts on a new read.  Some long read data will span multiple blocks.  If you wish to skip ahead from a BAM file without decoding in order to process in parallel, while still retaining the ability to handle long reads, you'll need to use the BAM index to get file offsets and at least partial decode from there (or create your own index up front).

**Comment by betteridiot** [comment]
Thank you all for the prompt replies. Knowing now that it is a convention, but by no means guaranteed, simpler in some respects, but more difficult in the long run. Nonetheless, thank you.

**Comment by betteridiot** [comment]
@jmarshall I found on that same [thread](https://sourceforge.net/p/samtools/mailman/samtools-devel/thread/AANLkTilCcBXyXt6zVgviEbKWuEhIxgzUV1noqGaZBcS0%40mail.gmail.com/#msg25496753) that Heng stated the following

> c) Now BAM header is guaranteed to be in BGZF blocks independent of
alignment blocks. An alignment will not bridge BGZF blocks if it is
shorter than 64KB uncompressed. Rob's extraflag idea has not been
implemented, yet.

Maybe I just didn't notice until I started doing low-level work on BAMs.
