### ISSUE TITLE
Clarification and expansion of CRAM Section 13.3: Codings

### ISSUE THREAD

**Issue by jmthibault79** [samtools/hts-specs#353]
I am working on updating the HTSJDK code base for better compliance with the CRAM spec, and I'm having some difficulty understanding how some of the Codings are intended to work.  While I have been able to work through some of my confusion through external sources, it would be helpful to me (and future implementors) if the spec contained everything necessary to implement these encodings.

### Beta coding
* is this exclusive to CRAM, or is this a widely-known encoding?  Neither https://en.wikipedia.org/wiki/Beta_Code nor https://en.wikipedia.org/wiki/Beta_encoder appear relevant here.
* update the examples table to include the offset and clarify that all values in a series are stored with the same bit length
* clarify that the length parameter is the (constant) bit length per value
* why would one choose Beta encoding?  (example given for Golomb is for a geometric distribution)

### Golomb
* how would one choose the M parameter?
* describe the decoding algorithm
* add an example for the Generate Codeword c-ii-B case

### Subexponential
* is there a widely-known source reference for this encoding?  the best I could find was a reference in [this paper](https://link.springer.com/content/pdf/10.1007/s10677-004-4254-0.pdf) with the same encoding/decoding algorithm described here.
* the decoding section should be rewritten.  The instructions to "append" and "form a run" are unclear in this context.  If my understanding is correct, this is equivalent:
  * count 1 bits (as **i**) until the 0 separator bit is seen
  * calculate **tail-len** from **i** as described
  * after the separator 0 bit, read **tail-len** bits and add **2^(tail-len)**

### Huffman
* link to https://en.wikipedia.org/wiki/Canonical_Huffman_code
* provide a brief overview of the process:
  * generate frequency table from input values
  * use frequency table to generate the Huffman codebook
  * canonicalize the codebook
  * decode using the canonical codebook

### Byte Array Length
* be more explicit that the data is stored as a block of array lengths, followed by a block of array values
* how are the length and values sub-encodings specified?  Do we set encoding ID (from the table in section 3) as parameter values?
* how do we pass encoding parameters to the sub-encodings?
* a table like that for Encoding in Section 2.3 would be helpful here

### Byte Array Stop
* why does this need a reference to an external block?
* is the external block encoded using one of the CRAM encodings, or are the byte arrays stored as-is?
* is this a copy/paste error?  "For example this could be a golomb encoding"

**Comment by jkbonfield** [comment]
Going through the CRAM specification to clarify it all is on my to-do list.  Until then, in brief:

- The cram specification covers decoding mostly, as it should, and doesn't need to describe how to choose a particular parameter nor under which circumstances this codec is better than another.  It can be helpful to do so, but it should be a footnote at best.

- CRAM suffers from the kitchen sink syndrome.  During early development it appears every bit-codec known to man was experimented with and added to the spec, although not all were implemented.  It needs a cull and is on my list of things to fix in V4.

- Beta codec isn't a CRAM invention.  If I recall it's just binary encoding to a fixed size, with an offset to permit A-B instead of 0-B ranges.  See https://www.oreilly.com/library/view/understanding-compression/9781491961520/ch04.html

- Golomb encoding: agreed it needs to be improved, however htslib has no code to read golomb or golomb rice codes as I never saw them in use in the wild.  Does the Java code even have anything to produce them?

- Sub-exponential: sorry I've no idea where this came from.  It's one of the codecs I wrote a decoder for but never an encoder (along with gamma) as I didn't see the point of it.  (I'd need to read it more carefully to understand the problems with the description.)

- Byte array length: think of this as a recursive encoding.  Using the same syntax you described the original encoding, you now have two of them for length and data.  Earlier on in the spec it describes "encoding<type>" meaning, which is what is being referred to in this section when it describes the data type as "encoding<int>" and "encoding<byte>".

  If the Java code decodes all lengths first followed by all values, meaning putting length + value into the same external code would yield "len len len val val val", then it differs to the C implementation!  My code treats it in the logical order: codec decode recurses down to get length (fetch) followed by len bytes of data (fetch), so they're interleaved.  This should indeed be spelt out explicitly.

- Byte array stop: I've no idea why it was set up to only permit external types instead of the recursive strategy employed by byte array len.  (You'd have to ask Vadim or Markus I guess.)  External is just a series of bytes - yes that golomb comment is a cut and paste error or a format conversion error (it was automatically converted from MS Word via xslt!).

What really all of this needs is example byte streams to demonstrate the use of these codecs.

**Comment by jmthibault79** [comment]
Unfortunately I don't have any information regarding which of these encodings are used in practice.  Java implementations [do exist](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/cram/encoding/EncodingFactory.java) but if htslib doesn't produce Golomb, Golomb-Rice, Gamma, or SubExponential I should probably deprioritize working on those.

Beta: yes this does look like simply another name for binary code (with offset).  The relevant section from the O'Reilly link matches perfectly.

Byte Array Length: I misunderstood the Java code on my first readthrough.  It does interleave like the C code: length, value, length, value.

Thanks for the quick response!

**Comment by jkbonfield** [comment]
The Golomb coding description is utterly wrong, as well as having no description of the decoder.  I probably didn't notice this as I never wrote an encoder or decoder as they didn't seem to ever be produced by Java.  (Maybe I just got lucky.)  I'm working on this right now.

It has r >= 2^{b} and not r >= 2^{b}-M.   It also states that case stores r+2^{b} and not r+2^{b}-M.

It also has an exception for M being a power of 2, which is redundant as the second case works anyway.  Eg N=8 => b=3 and 2^{b}-M = 0.  Thus r >= 2^{b}-M in all situations and we write out r in 3 bits; basically binary coding.  The exception to handle M for power of 2 adds needless comlexity and obfuscation (and is better described in the Golomb-Rice bit).

**Comment by jkbonfield** [comment]
Subexponential coding is indeed oddly described.  I've rewritten it now (PR incoming at some point).

I have also just found the source text for this, unreferenced and alarmingly plagarised (see the decode procedure on page 669 - identical text): https://link.springer.com/content/pdf/10.1007/s10677-004-4254-0.pdf

Anyway my new description I think is a lot easier, based on the suggestions you had and from the original paper as defined here: http://www.ittc.ku.edu/~jsv/Papers/HoV94.progressive_FELICS.pdf

That is *way* clearer than the CRAM spec.

**Comment by jkbonfield** [comment]
I'll be making a PR soon, but my work in progress is here:

https://github.com/jkbonfield/hts-specs/tree/CRAM_Is353

I'm now going through the Java and C code to double check exactly how they compare and to see if I am missing things.  The Java code does seem to support more codecs, but I've yet to see a single file using them.  I am unsure if this is because the code exists but is unable to be reached, or because of luck with the choices and what codecs are optimal (I've no idea how it decides which to use).

I am also a bit confused at some of the code.  Eg GolombIntegerEncoding.java and GolombIntegerEncoding.java both use ITF8 so I am baffled as to what their difference is.  The specification needs to be updated further to indicate which codecs work with which <Type> fields.  Huffman previously hinted at Integer only, but it also permits Byte in both of our implementations.  All very messy, but overdue a tidy up.

**Comment by jkbonfield** [comment]
For what it's worth, I finally found the region of code that decides on the codecs to use for the Java CRAM (CompressionHeaderFactory.java).  In htsjdk now this is hard coded to be fixed values (https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/cram/build/CompressionHeaderFactory.java#L79), mainly external.  Older versions could use beta, huffman, gamma and subexponential.

To get golomb and golomb-rice we have to go back to this commit in 2012: https://github.com/enasequence/cramtools/blob/9c4572fe408429b1c9d5104467e17e8392dd2708/src/main/java/net/sf/cram/stats/CompressionHeaderFactory.java#L436

That's a couple weeks before CRAM 1.0 was tagged in Vadim's repository and a full year before I started working on the C version.  I think it's safe to say we ought to cull these from the specification before anyone attempts to actually implement them!
