### ISSUE TITLE
VCF improvements: representation of complex or hard-to-type variants

### ISSUE THREAD

**Issue by ambarrio** [samtools/hts-specs#358]
It would be nice to have a case where SVs can be tagged as complex, specially in regions that are divergent and known to such cases, like HLA.

Our proposal would be to have a tag for the ALT field as follows:
##ALT=<ID=CPX,Description="SV of complex type">

I hope the following example help to illustrate this. Linked-Reads find NA24385 with one large rearrangement in HLADR locus (attached). You can clearly see that something is going on from the barcode heatmap and some clipped reads in strange orientations. Also, NA19240, has several UNK rearrangements in both HLA and IGH loci. Apart from many other unknown ones in gene deserts or complex loci.

![image](https://user-images.githubusercontent.com/146825/48156789-f8a52b00-e282-11e8-864b-606a73840ea8.png)
![image](https://user-images.githubusercontent.com/146825/48156816-05298380-e283-11e8-99b5-40ce63371dc7.png)

**Comment by d-cameron** [comment]
I'm dubious of the value of extending `ALT` field with events which do no describe what is actually going on. VCF already supports linking of related SV via the `EVENT` INFO field - the two SVs could be encoded in VCF as a set of `BND` records linked by a common `EVENT` identifier.

The issues with this approach are:

1.  When many SVs share the same EVENT, walking of the event is not unambiguous because which SVs are adjacent to which other SVs is not recorded. My work-around for this was to use an additional (non-standard) VCF field that contains the direct linkage information about which breakends are known to be adjacent to which other breakends.

2. Inability to encode ambiguities. If something is going on but the breakpoints cannot be resolved, then something needs to be written. In these scenarios, I favour reporting single breakends for unexplained CN transitions, or breakpoints with unknown partners. The VCF spec have an `IMPRECISE` flag, but you might also want an additional one (e.g. `INFERRED`) to make it clear that the you don't trust the actual variant call itself very much.

A CPX-style ALT allele has been previously suggested but was rejected as it is essentially giving up on actually resolving the variant and make downstream interpretation of such variants near impossible.

**Comment by d-cameron** [comment]
#469 should cover this use case

**Comment by ambarrio** [comment]
Thanks for that EVENTTYPE-PR. Good call on separating the concerns of calling and classifying. Using both $EVENT$ and $EVENTTYPE$ together would cover our proposed case of a very divergent haplotype SV with a customary tag.

I will close down this now.
