### ISSUE TITLE
htsget start-end 

### ISSUE THREAD

**Issue by rhdolin** [samtools/hts-specs#369]
Can someone explain how you'd process htsget start-end parameters if your repository has build37 and build38 VCFs? Thanks!

**Comment by mlin** [comment]
Hi @rhdolin (sorry for the slow reply) -- here are three ideas:

1. The htsget response usually includes the full VCF header with `##contig` lines which the client can check to ensure match with the desired reference sequence build.
2. Shortly with #322 we will add a precise way to request *only* the header which would allow the client to check the reference genome in advance of making any specific region query. It may be a while longer before this makes its way into running htsget servers, though.
3. I can also recommend setting up the server so that the HTTPS URL reflects the reference genome build. For example, the `https://data.institution.edu/htsget/1000genomes/b37/vcf` and `https://data.institution.edu/htsget/1000genomes/GRCh38/vcf`

**Comment by rhdolin** [comment]
Thank you Mike. I may be thinking about this wrong, but I'm envisioning a use case - I need to extract all variants in TPMT gene for my decision support application, and I know nothing about your genomic data server.  I was under the impression that there is sufficient variability in the representation of genomic build in the VCF Header, that you'd have to revert to manual inspection of the header to glean the build, which doesn't seem ideal. It seems as though it would be useful, to allow the query to request a range of positions, based on a build.  If I simply tell you I want all variants at Chr 6: 18128545-18155374, what can you do with that? This assumes that the person submitting the query already knows something about the files being queried. 
Anyhow, thanks for bearing with me as I try to think this through.
