### ISSUE TITLE
CRAM: indexing for multiple reference slices

### ISSUE THREAD

**Issue by jmthibault79** [samtools/hts-specs#376]
We should clarify that the CRAI and BAI indices should be ordered by reference sequence and alignment, with the Unmapped Slice last.

But what should we do about multiple-reference slices?  I'm picturing two scenarios here:
1. coordinate-sorted CRAMs with small ordered sub-slices combined into multi-ref Slices/Containers
2. non-coordinate-sorted CRAMs, in the pathological case consisting entirely of multi-ref Slices/Containers, each containing all references

We can handle case 1, by splitting multi-ref slice index entries into their constituent references.  (HTSJDK attempts to do this, but my understanding is that bugs in this approach exist currently.)

Case 2 seems hopeless to me.  Would it appropriate to state in the spec that indexes are explicitly not supported when reads are not coordinate-sorted?

**Comment by jkbonfield** [comment]
Ordering, I think we just require the index to be in the same order as the data.  I'm not sure what happens if we have reference IDs out of order in the input data (and thus in the index too).  It's possible to do this via `samtools cat`.   At first glances the index is in the same order as the containers, but not the file header, and it seems to work.  There would be problems if the went from ref A to B and back to A, but it's irrelevant whether we have A then B or B then A (I think). 

Htslib/Io_lib deals with case 1 by expanding up the RI data series during indexing and producing multiple entries pointing to the same location.  Eg "zcat foo.cram.crai" may show:

```
26      13446   1355    2989007587      881     605076
26      14701   308     2989613572      1308    637502
27      25      19879   2989613572      1308    637502
28      27      27217   2989613572      1308    637502
29      172     27504   2989613572      1308    637502
30      18      33802   2989613572      1308    637502
31      19      34426   2989613572      1308    637502
32      22      36101   2989613572      1308    637502
33      29      36320   2989613572      1308    637502
34      20      36627   2989613572      1308    637502
35      88      36030   2989613572      1308    637502
36      43      37439   2989613572      1308    637502
37      176     29308   2989613572      1308    637502
37      29409   8624    2990252410      1417    638740
38      125     38340   2990252410      1417    638740
39      103     38695   2990252410      1417    638740
40      175     39568   2990252410      1417    638740
41      7       39848   2990252410      1417    638740
42      40      39217   2990252410      1417    638740
43      74      39893   2990252410      1417    638740
44      60      40435   2990252410      1417    638740
45      51      40572   2990252410      1417    638740
46      528     40242   2990252410      1417    638740
47      91      41843   2990252410      1417    638740
48      462     41305   2990252410      1417    638740
49      23      42130   2990252410      1417    638740
50      27      18504   2990252410      1417    638740
50      18465   24776   2990892595      1253    640449
```

The columns are ref id, start, span (end-start+1), container file offset, slice offset ("landmark"), slice length.  Given we have multiple references per slice we see the same container offset, slice offset and slice length.  If we create a file containing multiple slices per container then we'll see the same container offset but differing slice offset/lengths (although still shared between references).  Eg:

```
25	64	4192	9501	544	7410
26	1	2829	17475	1001	590609
26	2731	1843	17475	591610	595272
26	4474	1488	17475	1186882	591174
26	5862	1091	1795561	998	598712
26	6853	852	1795561	599710	610817
26	7605	2984	1795561	1210527	596064
26	10489	3057	3602185	1016	590059
26	13446	1355	3602185	591075	588538
26	14701	308	3602185	1179613	77256
27	25	19879	4859087	649	40577
28	27	27217	4900338	1529	638328
29	172	27504	4900338	1529	638328
30	18	33802	4900338	1529	638328
31	19	34426	4900338	1529	638328
32	22	36101	4900338	1529	638328
33	29	36320	4900338	1529	638328
34	20	36627	4900338	1529	638328
35	88	36030	4900338	1529	638328
36	43	37439	4900338	1529	638328
37	176	37857	4900338	1529	638328
38	125	38340	4900338	1529	638328
39	103	38695	4900338	1529	638328
40	175	39568	4900338	1529	638328
41	7	39848	4900338	1529	638328
42	40	5190	4900338	1529	638328
42	5158	34099	4900338	639857	638869
43	74	39893	4900338	639857	638869
44	60	40435	4900338	639857	638869
45	51	40572	4900338	639857	638869
46	528	40242	4900338	639857	638869
47	91	41843	4900338	639857	638869
48	462	41305	4900338	639857	638869
49	23	42130	4900338	639857	638869
50	27	43214	4900338	639857	638869
51	376	42996	4900338	639857	638869
52	32	18063	4900338	639857	638869
52	18003	25621	4900338	1278726	630201
53	1	45835	4900338	1278726	630201
54	171	45738	4900338	1278726	630201
55	300	80973	4900338	1278726	630201
56	3	89923	4900338	1278726	630201
57	36	30583	4900338	1278726	630201
57	30569	61546	6809300	1966	636219
57	92015	675	6809300	638185	637292
58	347	106036	6809300	638185	637292
59	85	128001	6809300	638185	637292
60	9	128875	6809300	638185	637292
61	2	44344	6809300	638185	637292
61	44264	90651	6809300	1275477	642404
61	134822	2882	8727216	1485	640325
62	80	155267	8727216	1485	640325
63	2	158620	8727216	1485	640325
```

I'm still unsure whether multi-slice containers are worth the hassle though!  In theory we could use them to good effect if we moved more meta-data over to the container header, but that would need more work on CRAMv4.

As for case 2, I agree it's hopeless.  I don't see any good way of indexing non-position sorted data without using a completely different index format.

**Comment by jkbonfield** [comment]
Hmm, whether right or not I don't know, but picard appears to differ to samtools here:

```
# Create 10 bam and cram files with snippet from first 10 chromosomes
$ for i in `seq 1 10`;do samtools view -@8 -O cram -o /tmp/_$i.cram ~/scratch/data/9827_2#49.cram $i:20000000-25000000;done
$ for i in `seq 1 10`;do samtools view -@8 -O bam -o /tmp/_$i.bam ~/scratch/data/9827_2#49.cram $i:20000000-25000000;done

# Concatenate in random order
$ samtools cat /tmp/_{9,2,1,6,10,4,7,8,3,5}.cram -o /tmp/_.cram
$ samtools cat /tmp/_{9,2,1,6,10,4,7,8,3,5}.cram -o /tmp/_.cram

# Count entries
$ samtools view -c /tmp/_.bam
935949
$ samtools view -c /tmp/_.cram
935949

$ /usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_.bam ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF 2>/tmp/err | egrep -cv '^@'
935949
$ /usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_.cram ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF 2>/tmp/err | egrep -cv '^@'
98188
```

I haven't tried the latest version, but this is close.  It appears to not like the out of order nature of cram.  No errors are reported, just the usual diagnostic chatter.   I can copy this over to htsjdk if you wish, but initially we need to decide what the spec claims is correct even.  (It probably says nothing at all...)

**Comment by jkbonfield** [comment]
On further investigation, I see this isn't ideal for BAM either with Picard.

header-sorted vs non-header-sorted files:

```
#  Create input
$ samtools cat /tmp/_{9,2,1,6,10,4,7,8,3,5}.bam -o /tmp/_.bam; samtools index /tmp/_.bam
$ samtools cat /tmp/_{1,2,3,4,5,6,7,8,9,10}.bam -o /tmp/_o.bam; samtools index /tmp/_o.bam

# Create region list
$ (samtools view -H /tmp/_.bam;for i in 3 8 2 4;do echo -e "$i\t22000000\t24000000\t+\ttarget_$i";done) > /tmp/_reg.list

# Query header-sorted: OK
$ usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_o.cram ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF INTERVAL_LIST=/tmp/_reg.list  2>/dev/null | egrep -cv '^@'
149025
$ usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_o.bam ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF INTERVAL_LIST=/tmp/_reg.list  2>/dev/null | egrep -cv '^@'
149025

# Query out-of-order references: silent failure
$ /usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_.cram ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF INTERVAL_LIST=/tmp/_reg.list  2>/dev/null | egrep -cv '^@'
110551

$ /usr/bin/java -jar ~/work/picard-2.18.15.jar ViewSam INPUT=/tmp/_.bam ALIGNMENT_STATUS=All PF_STATUS=All REFERENCE_SEQUENCE=$HREF INTERVAL_LIST=/tmp/_reg.list  2>/dev/null | egrep -cv '^@'
110551

# With samtools
$ for i in _.cram _.bam _o.cram _o.bam;do samtools view -@4 -c /tmp/$i $(for i in 3 8 2 4;do echo $i:22000000-24000000;done);done
149025
149025
149025
149025

# Validation against original data file (Picard also matches this, for both bam and cram)
$ samtools view -@4 -c ~/scratch/data/9827_2#49.bam $(for i in 3 8 2 4;do echo $i:22000000-24000000;done)
149025
```

I'm not sure where 110551 is coming from.  It's 38474 short of the correct value, which is the number of records that should be retrieved from chr 3.  Why miss the first one?

**Comment by jmthibault79** [comment]
> There would be problems if the went from ref A to B and back to A, but it's irrelevant whether we have A then B or B then A (I think)

That's a good point: More precisely, preventing A-B-A is what we want.  Thinking solely of the pathological cases, only coordinate-sorted will satisfy this.  Is that too restrictive with real-world data?  (e.g. queryname-sorted with names starting with their references.)  Maybe the best implementation is to start the index optimistically, erroring out only when the data demands it.

With this approach, index requirements become:
1. Non-repeating sequence IDs
2. Within a Sequence ID, monotonically increasing Alignment Start
3. Within a (Sequence ID / Alignment Start) pair: monotonically increasing Container Offset
4. Within a (Sequence ID, Alignment Start, Container Offset) triple: monotonically increasing Slice Offset

Maybe 3 and 4 are not really necessary here.  How likely is it that we'll have so many reads at the same location that we need to store them in multiple Slices or Containers?  Or maybe it's worthwhile to account for it just in case.

**Comment by jmthibault79** [comment]
Thanks for the clarifying index examples btw!

Would you mind filing a bug report in HTSJDK for what you've found?  Seems like it's a more general problem than CRAM.

**Comment by jkbonfield** [comment]
Where to go with this issue?

- I think we can agree that the index requires a coordinate sorted CRAM file.  This is the same requirement we have on BAM.

- The statement that "All indexing information can be obtained from container headers" is misleading.  It is for all indexing information for containers that don't have ref id -2.  Those with ref -2 need to be partially decoded to obtain the RI data series.  We should be explicit here has it helps to explain how to build the index.

- "Please note that all slices must be listed in index le": I remember this not being true in the early days, although it's not a bad idea now.  I think we had the requirement that every reference sequence must have the first slice covering it listed in the index, but it was permissible to skip some slices and thus reduce index size.  The decoder would simply find the first location listed in the index and then start skipping forward from there until it overlapped the exact query region.  I'm not sure why we tightened this up - probably because it was pointless: save a tiny amount of space at the cost of far coarser random access granularity.  Ie after a lot of verbage, keep as is. ;-)

- Be explicit for ref seq id -1:  alignment start and alignment span must be present, but should be ignored.  (My implementation appears to create them as 0 and 1.  I'm not sure why 1 for span; ie guess it's pos 0 to 0 inclusive.)

- Be explicit for ref seq id -2: every reference sequence must have a line in the index, even if multiple references are packed into the same slice.  In this case the sequence id must be written explicitly with the correct value (not -2), each having their own alignment start and span, and the container offset, slice start and slice bytes fields will be duplicated for every reference within this slice.  Thus in order to build the reference the RI data series will need to be decoded.

Anything else we need to document here?

**Comment by jmthibault79** [comment]
That looks right to me, thanks.

**Comment by cmnbroad** [comment]
👍 as well.

**Comment by jkbonfield** [comment]
I'm happy to work on a PR describing this if no one has started one yet.

**Comment by jmthibault79** [comment]
Thanks, that would be great.
