### ISSUE TITLE
CRAM spec read feature clarifications

### ISSUE THREAD

**Issue by cmnbroad** [samtools/hts-specs#408]
A few somewhat nitty questions on the CRAM spec (section 10.6, Read Features) based on some code cleanup I'm doing in htsjdk. I can make a spec PR based on the results of the discussion.

From the part under "Base substitution codes (BS data series)":

> There are 5 possible bases ACGTN, 4 possible substitutions for each base and 20 substitutions in total.

That seems to imply that only upper case differences are represented as substitutions, and that source case is otherwise preserved (?) However, htsjdk has code that handles `Substitution` features that are case transitions, but only on read; it only *writes* `Substitution` read features in the case where the reference and read base are different, but both upper case. Otherwise if they're different it generates a `ReadBase` feature. `ReadBase` features are referenced in the spec, but not spelled out anywhere. Is the intent that preservation of base case is prescribed by the spec, or is that left to implementation policy ? Is it required that `ReadBase` features are used to represent case differences, and/or are case `Substitution`s legal ?

> Same-frequency ties are broken using alphabetical order

The htsjdk implementation breaks ties using the order 'ACGTN', which isn't alphabetical order. Although I don't think it matters since it doesn't affect the file format itself.

> The whole substitution matrix is written as 5 bytes, one for each reference base in the alphabetical order: A, C, G, T and N

Not alphabetical...

> Note: the last two bits of each substitution code are redundant but still required to simplify the reading. 

Not sure how to interpret this ?

**Comment by jkbonfield** [comment]
Regarding case, I doubt it was intended to consider case as important as this was originally aimed to replace BAM which is already ignoring case (it munges it all to uppercase).  The decision was before my time though.  My input here was simply to use a lookup table instead of the base itself.

If we wish to consider a case-preserving CRAM then we'll either need to expand on this further as punt it to CRAMv4 or spell out explicitly that all base case changes need to be encoded as a read base feature (B).   My gut feeling is to clarify that whether an implementation wishes to consider case changes as a difference that needs encoding as a feature is implementation dependent - we can state that explicitly in a footnote.  FWIW, htslib treats c and C as equal.

I don't think read base needs explicitly spelling out - it's a base.  We could clarify by saying it has to be upper case, or maybe it has to be one of the recognised IUPAC ambiguity codes, etc, but I think it's basically the byte that cases from the input source data and anything beyond that is implementation specific checking.

As for order - yes we should get rid of mentions about alphabetical.  The bit about ties is unnecessary, and even the bit regarding how to compute the table is too really.  It should be up to the implementation to decide and I don't see why the specific codes must be prescriptive.  Even though the matrix was my idea, it looks like I never implemented any code to optimise it!  So I definitely don't follow the rule of sorting things by frequency.  I'm sure I had reason for it... I wonder how much gain it is. :-)

"Note: the last two bits of each substitution code are redundant but still required to simplify the reading":  I think this refers to the fact we can deduce the last one as we know all values from 0 to 3 inclusive are shuffled in the matrix, so the 4th is obvious by elimination.  Maybe we should just delete the sentence though if it's not clear.  It doesn't add much.

[Incidentally I've never liked that feature B also outputs a quality score! It's a pain and I feel it shouldn't be included unless the preserve-quality-scores flag is unset, but that ship has sailed.]

**Comment by jkbonfield** [comment]
In answer to my question, manually optimising the matrix for 10 million NovaSeq reads gave a 15% reduction in the compressed size of the BS field.  The overall impact though was tiny as the error rate / SNP rate was small, so around 0.1% total file saving!

I'll try again with ONT where the number of BS calls will be much higher.

**Comment by 0xorial** [comment]
Could you please explain what is the reason to use substitution matrix instead of just storing the final substituted letter in the read feature? That would have taken the same amount of space made decoding much simpler...

**Comment by jkbonfield** [comment]
The logic is that on genomes with strong GC content bias or using machines with specific error types on base calling, an appropriate substitution matrix can be used so the entropy of the substitution codes data series is reduced.  The difference can be quite significant to that data series, but overall it's actually not that significant compared to all the other features in CRAM, so the point is perhaps a valid one.  Hence in practice we typically don't actually try to optimise this.  (I should probably explore it again though to see if it differs now we have more technologies / platforms out there.)

I disagree though that it makes decoding complex.  It's just adds a minor lookup table.

**Comment by jkbonfield** [comment]
> > There are 5 possible bases ACGTN, 4 possible substitutions for each base and 20 substitutions in total.
> 
> That seems to imply that only upper case differences are represented as substitutions, and that source case is otherwise preserved (?) However, htsjdk has code that handles `Substitution` features that are case transitions, but only on read; it only _writes_ `Substitution` read features in the case where the reference and read base are different, but both upper case. Otherwise if they're different it generates a `ReadBase` feature. `ReadBase` features are referenced in the spec, but not spelled out anywhere. Is the intent that preservation of base case is prescribed by the spec, or is that left to implementation policy ? Is it required that `ReadBase` features are used to represent case differences, and/or are case `Substitution`s legal ?

I'm not sure I follow this, but in testing picard-2.26.11.jar case mismatches for the same base (eg "a" vs "A" and "A" vs "a") don't generate base substitutions or literal base (BS and BA) elements.  Further more "a" vs "C" is treated the same as "A" vs "C", and vice versa.  That's writing.

I don't have any way to generate lowercase BA values to test the decode side, short of hacking the code somewhere, but I think it's not interesting.

Given BAM is case insensitive and we want to round-trip to it, I'll add an explicit statement about case.

> > Same-frequency ties are broken using alphabetical order
> 
> The htsjdk implementation breaks ties using the order 'ACGTN', which isn't alphabetical order. Although I don't think it matters since it doesn't affect the file format itself.
> 
> > The whole substitution matrix is written as 5 bytes, one for each reference base in the alphabetical order: A, C, G, T and N
> 
> Not alphabetical...

Oops.  I hadn't noticed when writing this that N isn't in the alphabetical order!

It's a good point though things like breaking ties is irrelevant for the file format itself.  Indeed htslib doesn't even bother optimising the order at all.  So I've completely rewritten this section now.  Hopefully it makes more sense.

> > Note: the last two bits of each substitution code are redundant but still required to simplify the reading.
> 
> Not sure how to interpret this ?

Given the following example:

Ref C:  subst A=1, G=0, T=2, N=3

We'd write 01 00 10 11 for A, C, G and T codes.

Given there are only 4 alternatives to C (AGTN), by the time we know A=1, G=0 and T=2 then the only thing left is N=3, so it's arguably redundant to explicitly state it.  However the header is a byte-oriented format and we have 2 bits spare so they may as well be written out for simplicity of implementation.

It looks like I've already deleted that statement though (it's only in the v2.1 doc).  It just added more verbage without really explaining anything.
