### ISSUE TITLE
SAM spec versioning

### ISSUE THREAD

**Issue by mckinsel** [samtools/hts-specs#47]
The `@HD::VN` tag tells the "format version" for the SAM file. It has to match \d+\.\d+ . For example, samtools sort writes "VN:1.3" to files it creates.

Prior to commit 321f786cfed538cb3a8b6e38c4a9a2ec19fcd99a , the SAM spec had its version and revision written in the title. It would say something like "The SAM Format Specification (v1.3-r624)". Now, there's no version number, but there is a git commit hash. However, that cannot be written into the SAM file.

So, if I produce a SAM file that I'm sure conforms to some copy of the spec, how should I indicate that in the VN tag? Alternatively, if a SAM file says its version is 1.5, how do I find the corresponding spec?

**Comment by jkbonfield** [comment]
I just spotted this problem again and it still needs fixing.  Can we just manually add a version number to the file?  The old "r624" bit is essentially the equivalent of a git revision and it may be bumped for minor typo fixes or clarifications, without a need to change the core version number.

So both are necessary.

**Comment by jmarshall** [comment]
To my mind, the problem is that VN values are mentioned *only in examples* in the spec.  What this needs is not an addition to the title of the document, but rather a section discussing the version number in the VN and what it means.

**Comment by jmarshall** [comment]
Since be8e0643c2452c6375445cf2b5ed95eb4a76bb21 (PR #218), the spec introduction notes the current version number and discusses VN, and there is an appendix noting the significant changes implied by different values for VN.

So I think this issue has been addressed. The final question (_if a SAM file says its version is 1.5, how do I find the corresponding spec?_) is now #194 — or answered by “due to the appendix in the most recent spec, you don't need the corresponding spec”.
