### ISSUE TITLE
Clarify MD tag description

### ISSUE THREAD

**Issue by nh13** [samtools/hts-specs#485]
@jmarshall and I were having a discussion on pysam about the MD tag: https://github.com/pysam-developers/pysam/issues/895

The MD regex is clear that we need zeros between adjacent mismatches, or after an insertion.  This makes the MD tag alone able to describe the reference sequence.  Nonetheless, for SAM, we most often have a cigar, so the extra zeros I do not believe are needed in this case. For example, `10A5^AC6` is underspecified if a CIGAR is not given, since a cigar `10=1X5=1D1X6=` or `10=1X5=2D6=` could both "work" with the MD tag.  The former should be `10A5^A0C6` (with the `0` between the deletion and next mismatch), and the latter should be `10A5^AC6`.  With a CIGAR (even using `M` instead of `=` or `X`) it is clear. 

What do folks think about MD tags that do not have the zero padding?

**Comment by colinhercus** [comment]
Hi Nils, I think they're a waste of space. Colin

**Comment by nh13** [comment]
@colinhercus zeros or MD tags, or both?

**Comment by colinhercus** [comment]
The zeroes

**Comment by colinhercus** [comment]
MD tag is optional so not necessary unless user requests it

**Comment by jkbonfield** [comment]
IMO the purpose of this tag is to go from sequence to reference directly.  While it is stated that it must be compatible with the CIGAR string, it doesn't say that it must be used in conjunction with CIGAR.  I think that is an additional requirement that we haven't previously needed.

Therefore IMO the zeros should be mandatory.

**Comment by jmarshall** [comment]
The MD text in the original (pre-TeXification) SAM specification was

> MD    Z
> String for mismatching positions in the format of `[0-9]+(([ACGTN]\|\^[ACGTN]+)[0-9]+)*`
>
> Mismatches/insertions/deletions in clipped sequences are not counted.
>
> The MD field aims to achieve SNP/indel calling without looking at the reference. SOAP and Eland SNP callers prefer such information. For example, a string “10A5^AC6” means from the leftmost reference base in the alignment, there are 10 matches followed by an A on the reference which is different from the aligned read base; the next 5 reference bases are matches followed by a 2bp deletion from the reference; the deleted sequence is AC; the last 6 bases are matches. The MD field should match the CIGAR string, although an SAM parser may not check this optional field.

The current text omits the SOAP/Eland reference and the “although […]” bit at the end, but is otherwise mostly unchanged.

This is a woefully incomplete description of how this MD string is supposed to be formed, so whatever conclusion we come to about 0-padding, the description in SAMtags needs to be fleshed out beyond the current regular expression and overly simple example.

----

As noted on the linked pysam issue (pysam-developers/pysam#895), to reconstruct the reference sequence you do in fact need all three of SEQ, MD, and CIGAR — MD does not encode insertions, so you need to parse CIGAR to use the `I` operators to omit any inserted bases that are present only in SEQ. So needing to parse the `D` operators as well to know how many deletion bases to read after `^` would not be beyond the pale, but it would be a change from the status quo (and would presumably break some existing programs that parse MD tags).

IMHO a delimiter between deleted-bases and any following mismatch-bases should be required, as otherwise (human) reading of the MD tag in isolation is confusing. We could introduce some other delimiter (e.g. `10A5^A$C6` for Nils's former case) but that would be a breaking change. The spec's regular expression is already extremely suggestive that the intention was for strings of letters to **alternate** with strings of digits, so the already syntactically correct delimiter is `10A5^A0C6`.

OTOH IMHO the requirement for a delimiter between adjacent mismatch bases is harder to justify, so I would be happy to omit those pointless `0`s that do just waste space. (However it's hard to predict what effect that might have on existing programs that parse MD tags.)

What if any changes would be sensible here really comes down to what programs exist that produce and consume MD strings. The canonical producer is `samtools {fillmd,calmd}`, and it produces MD strings with these zeros and always has done so. I haven't yet looked at bwa or other aligners that might produce MD. The pysam `get_reference_sequence()` function that Nils ran into is the first thing I've seen that actually interprets MD values. What others are people aware of? How similar is/was the SOAP and Eland notation that the spec previously mentioned?

**Comment by jkbonfield** [comment]
Ok good point - to reconstruct reference I agree CIGAR is necessary.  I forgot that MD doesn't include any indication of insertions.

The question has come up several times it appears, for example in 2011:
http://seqanswers.com/forums/showthread.php?t=8978

Heng has also blogged about the need for zeros:

https://lh3.github.io/2018/03/27/the-history-the-cigar-x-operator-and-the-md-tag

**Comment by colinhercus** [comment]
Back in 2008 Novoalign left the zeroes out and I remember it caused an
issue but not what program had the issue. I added zeroes in after
discussing with Heng Li.

**Comment by nh13** [comment]
Here’s htsjdk’s Implementation: 
- https://github.com/samtools/htsjdk/blob/942e3d6b4c28a8e97c457dfc89625bb403bdf83c/src/main/java/htsjdk/samtools/util/SequenceUtil.java#L946

Here’s BWA: 
- https://github.com/lh3/bwa/blob/f090f93460a0379d78a97bfa6133bae5bc8283a6/bwa.c#L169
- https://github.com/lh3/bwa/blob/f090f93460a0379d78a97bfa6133bae5bc8283a6/bwase.c#L201

My reading is that they both follow the spec (zeros).  But like @jmarshall said, you need the CIGAR to reconstruct the reference, and so the  need for extra zeros is confusing. 

For more context why this is an issue is that in many places (htsjdk, fgbio, and now [samwell](https://github.com/myriad-opensource/samwell/blob/master/samwell/sam/sambuilder.py), I use “builder” classes for building SAM records programmatically rather than relying on static test files, which are brittle and difficult to extend. So when I have tools that use the MD to reconstruct the reference, I have to hand make the MD tag. Adding the extra zeros has been to this point non-intuitive and as you can see I have forgotten to add them in many occasions.

**Comment by jkbonfield** [comment]
Understood.  We have a GA4GH File Formats conference call in 20 mins so we can get back to you after that.  Whatever the outcome, I think we all agree the specification needs clarification.  Thanks for raising this.

**Comment by jkbonfield** [comment]
General consensus at the meeting was 1) yes it really needs clarifying (@jmarshall volunteered) and 2) unless we can find a compelling reason why the zeros must be removed then we'll play it safe and document them.

That's not to say someone could write a better MD parser that copes without the zeros, but we'll write it up such that they're there as intended.

The "compelling reason" for part 2 would probably be if it can be show that, say, ONT data MD tags bloat the files by a significant percent with zeros, and not without.  I haven't done the tests, but even on that data I'm not expecting more than a couple percent bloatage.

**Comment by colinhercus** [comment]
It also gets bloated on Bi-Seq alignments.

DRR019431.2     83      1       249150593       70      101M    =
249150525       -169
 AAAAAATCTCTAATAAAAATCCCACCCTCCTACAAACCCAAAAAAAACAAACCTAAAATCCTACTCCCTCATCCTCCCACCTATACAATTCCGCCTTTTCN
  DDDDDDDDDEEDDDDDDDDDDB?<DDDDDDEDDD@8DDDDDDDFFFEFHHHHHJJJJIHIHG@HGJJJIJJIJIGIHF?JJIIIGJJJHHHHHFFFFD=1#
  PG:Z:novoalign  AS:i:6  UQ:i:6  NM:i:24
MD:Z:0G0G2G0G5G0G1G0G0G0G0G12G2G0G6G2G0G3G3G1G0G4G21G15T0       PQ:i:

**Comment by nh13** [comment]
Why can’t we say that the zeros can be omitted when a cigar is present?  

With a cigar it is completely deterministic, and the parsing complexity is no worse (faster perhaps because the MD string is shorter, but we have to loop through the cigar in parallel). Is the issue that implementations must change to support the new output? I’ll sign up for changing the htslib and htsjdk methods for parsing the MD in both formats transparently. Could do pysam too as I may need pythonic access. Thoughts?

**Comment by jkbonfield** [comment]
The problem is that it is a defacto spec change and we don't know what the impact will be.  While it's true that the specification is poor and underdefined, most implementations do put the zeros in and this is what people expect.

I agree they're not necessary, and like Heng with hindsight I'd say MD is a poorly designed tag anyway.  However changing the definition may have unintended consequences and it was felt the safe option is to document the way that current implementations work.

For example CRAM auto-generates MD.  During CRAM encode It checks whether the auto-generated one matches the current MD tag and if not it stores it verbatim instead (this is necessary due to a number of buggy tools out there that write incorrect MDs).  If we stopped writing zeros, our BAMs would shrink while our CRAMs would grow.

**Comment by jmarshall** [comment]
Proposed text describing the status quo (so with the ‘excess’ `0` delimiters) is now PR #500.
