### ISSUE TITLE
htsget OpenAPI endpoint repetition

### ISSUE THREAD

**Issue by mlin** [samtools/hts-specs#489]
The [htsget prose spec](https://github.com/samtools/hts-specs/blob/master/htsget.md) describes two endpoints,

```
GET /reads/<id>
GET /variants/<id>
```

which share a common mechanism of operation, while differing in the returned dataype and a few  details (e.g. valid "fields"). It was a historical/evolutionary path to this design.

Our [OpenAPI spec](https://github.com/samtools/hts-specs/blob/master/pub/htsget-openapi.yaml) describes the two endpoints and largely duplicates the parameter and response schemas between them. This is ok for now with just the two endpoints, but may become more problematic if htsget servers want to start exposing additional datatypes in the future, or don't want to call the endpoints "reads" and "variants" for whatever reason.

Is there a way to refactor this to reduce the duplication in the OpenAPI spec, without necessitating an actual protocol change? Making the `{reads,variants}` component itself a variable is one obvious idea, but how would we convey constraints about the filter fields and such in that case?

**Comment by mlin** [comment]
@brainstorm soliciting your input on this if you have a moment; cc @jmarshall @jb-adams

**Comment by brainstorm** [comment]
I did look into that when I was writing up the OpenAPI spec, this is what I got from upstream devs of OpenAPI v3:

https://twitter.com/PermittedSoc/status/1100013454327508994

I just included you in the thread, need to check the changelog and see if it's possible nowadays.

**Comment by jb-adams** [comment]
It's possible to define some reusable `parameters` and `responses`.

OpenAPI allows for reusable parameters in `#/components/parameters`
Between `/reads/{id}` and `/variants/{id}`, the `referenceName`, `start`, and `end` parameters appear to be exactly the same. So we could define each once in `components/parameters` and reference them in each API route. `fields`, `tags`, `notags` are unique to the reads API, so nothing needs to be done there. Even `id` could work across both if we are ok with generalizing the language.

OpenAPI allows for reusable responses in `#/components/responses`
We could define a single schema for `400`, `404`, etc responses and import them in each API.

Is this what this issue is about?

**Comment by brainstorm** [comment]
I recall trying a similar refactor but the (online) editor was marking it as syntax error and wouldn't allow me to proceed... perhaps I was missing something back then, so please do try what you are proposing, a more compact/refactored OpenAPI definition would be great! :)

**Comment by jb-adams** [comment]
Ok, I'll give this a shot and submit a PR
