### ISSUE TITLE
Parentheses in RNAME

### ISSUE THREAD

**Issue by rwinand** [samtools/hts-specs#526]
I was running the latest version of Picard (v2.23.3) on some Influenza samples and ran into an issue because the sequence names contained parentheses which are no longer allowed in the SAM specification. I read pull request #333 and the reasoning behind the tightening is compelling but it leaves me with a problem. A large number of Influenza (reference) sequences that are available contain parentheses. The following is a random example: `A/mallard_duck/Kagoshima/KU116/2015(H5N8)`. As you can see, the subtype is mentioned between parentheses and these are no longer allowed. 

I also found [issue #1295](https://github.com/samtools/htsjdk/issues/1295) where the same issue occurred but I could not find any further information about that case.

Is there any chance that the specification will be relaxed to allow for these characters? If not, I will have to look for a workaround but I fear many people working with Influenza will run into the same issue.

**Comment by jmarshall** [comment]
In the samtools/htsjdk#1295 case, there were four out of 140 thousand contigs with names like

> ENSMUST00000167415.7|ENSMUSG00000086429.9|OTTMUSG00000034748.3|OTTMUST00000090750.1|Gt(ROSA)26Sor-204|Gt(ROSA)26Sor|551|antisense|

The author of that issue was insufficiently moved to open an issue here, so we didn't investigate further. In particular, as discussed [on the ga4gh-fileformats list](https://groups.google.com/a/ga4gh.org/g/ga4gh-fileformats/c/VvzhEt9FgLc/m/SYu3h5vwCQAJ) (that link might not be public though I thought it was supposed to be…), in that case it seems that the FASTA contig names would be more usefully split up during mapping to produce an `@SQ` line like

```
@SQ	SN:ENSMUST00000167415.7	LN:551	DS:|ENSMUSG00000086429.9|OTTMUSG00000034748.3|OTTMUST00000090750.1|Gt(ROSA)26Sor-204|Gt(ROSA)26Sor|antisense
```

or similar, thus sidestepping the problem.

However your influenza case does not appear to be similarly able to be worked around. Can you point us at a FASTA reference file or other source showing a larger list of such influenza reference sequences? (So we can see more of the context of various RNAMEs in your field.)

**Comment by rwinand** [comment]
Thanks for the reply. The link that you mentioned is indeed not public so I can't read it but I already thought that given the fact that I could not find a follow up to that issue, the author would have circumvented the issue.

As to your question, there are a few examples but this one from NCBI is a very large one:
https://ftp.ncbi.nih.gov/genomes/INFLUENZA/influenza.fna.gz

Also, when you go to the [NCBI Influenza Virus Resource](https://www.ncbi.nlm.nih.gov/genomes/FLU/Database/nph-select.cgi?go=database) you can download any number of sequences and they will have the viral segment (e.g. HA, NA, ...) between parentheses.

**Comment by jkbonfield** [comment]
The main goal of the tightening up was to reduce potential problems for other formats and not to cause problems for SAM. Eg quotation marks, angle brackets and commas can be problematic in VCF Contig lines (IIRC - I forget the exact nuances so treat that as an example rather than fact), so permitting them in SAM would be just saving up pain for later.  If we permitted them in SAM then people would still need to do some local renaming to get them working elsewhere, so that renaming may as well be done at the start so as to be consistent across all the formats.

However possibly we need to tweak the list of permitted symbols more.  It would be a great help if you could scan all other local reference files you have to identify any other meta-characters that are in the restricted list too, so we don't have multiple rounds of discussions and updates.

We have a conference call tomorrow and this is now on the agenda thanks to jmarshall.

I wonder also whether there is room for smarts in the implementations (maybe warnings rather than hard failure) and/or a relaxation of SQ AN (alternative name)?  Eg I could imagine a case where a malformed reference name gets automatically renamed to escape the bad chars, with a warning, and an AN record put in containing the original name.  This AN may not be compatible with downstream formats, but it wouldn't be the one put into VCF Contig lines either.  It's a pragmatic middle ground.

**Comment by rwinand** [comment]
After going through the references I did find a few sequences that also used the square brackets ('[' and ']') but these did not end up in the collection of reference sequences that I am currently using. However, I do agree with the premise that the tightening needed to be done to be compatible with other formats. Therefore, I don't think that exceptions like the square brackets should be allowed even if it means that I will have to edit some of these names before I can use them if the time comes. 

The parentheses on the other hand are in almost every identifier that I use so while in theory, I can also rename them, it would be much more cumbersome to do so. Until now, I didn't have any issues with using the parentheses in a downstream analysis but I can see that they can potentially lead to issues in some formats but I haven't encountered that situation yet.

I think that your proposal to do a sort of smart implementation also has merit. I'm not knowledgeable enough to know exactly what the effect would be on downstream analyses when adding these names in SQ AN but if a warning could be given that some characters are not allowed and I can retrieve the original name from there, that would also work. Only giving a warning might be too weak as it will not encourage people to change naming in the future and for most of these characters I agree that they should not be used.

If it would prove to be too difficult to allow the parentheses as it would pose issues with other formats, I will have to change the identifiers for these sequences and I'm sure that once the new rules become more common knowledge, new references will be named differently. This is just to say that even though it would be very nice for me to be able to keep working with the current names (either by allowing the parentheses or going with the smart implementation), I understand that sometimes things need to change in order to get everything consistent even if it breaks some things on the way.

**Comment by jkbonfield** [comment]
Your fasta file raises another question however - are spaces permitted in reference names?

The NCBI description of FASTA for Blast explicitly states spaces aren't to be part of the identifier: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp

When I've used it myself, I've always considered any white-space to be the end of the name.  Has the community now moved on to accepting only tab as a delimiter and permitting space?  That would seem surprising.  I see bwa mem truncates after the first white-space for purposes of emitting the RNAME field.

If we work on that philosophy, none of your entries are malformed.

(However I can see it may be useful to be able to specify a delimiter and to sanitize everything that comes before it.  I'm working on a perl script which ultimately will be places in samtools/misc directory.)

**Comment by rwinand** [comment]
You are right, the FASTA that I referenced does contain spaces which will truncate the names. The sequences that I use most are from a different source that contains most of the same sequences (but they are not available without registering first) and in those names, the spaces are replaced with underscores or even forward slashes.

I have decided that I'm just going to rename the identifiers at this time and format them in a way that is most convenient for me. I'm guessing that in the long run, the benefit of adhering to the standard will outweigh the time I need to spend now for reformatting. The script that you mentioned would certainly be helpful if others also want to reformat the names so that they adhere to the standard. 

I would like to thank you and jmarshall for looking into this but at this time I will be closing the issue as it is no longer applies to me.
