### ISSUE TITLE
Use GitHub releases for built PDFs

### ISSUE THREAD

**Issue by michaelmhoffman** [samtools/hts-specs#568]
`MAINTAINERS.md` seems to lament some difficulties caused by having the PDFs checked in. You can get around some of these by switching distribution to GitHub's releases feature. The GitHub `gh` command-line client makes it easy to update the files in the release.

```sh
gh release create latest
gh release upload SAMv1.pdf --clobber
```

Biggest downside, of course, is that any links to the built PDFs from elsewhere on the web will break.

**Comment by jmarshall** [comment]
Aspects of this have been discussed on #328. IMHO breaking existing links to the specification documents is an insurmountable downside, and requiring maintainers to have extra tools and expertise would be unfortunate.

**Comment by jkbonfield** [comment]
We also previously discussed the idea of using tags, which obviously is also tied up with releases.  It's a bit messy because we basically have multiple projects within one github project, so a tag for SAM-X would contain VCF-Y, BED-Z and so on. where Y and Z may not be official version numbers but simply some point inbetween.  Github really isn't set up for multiple release streams, so they'd all be listed sequentially making it harder to find the latest version of the spec you are interested in.

We discounted tags because it could be confusing and also because version, say, SAM-1.5 doesn't mean that's the document to look at, as it may be 1.5+3 commits which is essentially still 1.5 but with typos fixed and clarifications added.

So I'm with @jmarshall here.  If we need anything extra, it'll be some basic tooling to checkout, rebuild, copy the new PDFs over, add a commit with a standardised message ("Updated PDFs"), and push back to master.  We're sometimes a bit slow doing things manually, but it also gives us flexibility to buffer things up a bit if we know we have a flurry of merges incoming.

**Comment by jmarshall** [comment]
Yes, I was also going to link to the previous discussions of specification versioning at #316 and as linked from there, but from `--clobber` I get the impression that @michaelmhoffman was floating the idea of just having one rolling GH release that maintainers would update with new copies of PDFs to overwrite the previous assets.

> If we need anything extra, it'll be some basic tooling to checkout, rebuild, […], and push back to master.

Fortunately we have the John-bot for that :smile:

Indeed, there's a one week timer going off later today that I'll take care of if one of the VCF maintainers doesn't remember first.

**Comment by michaelmhoffman** [comment]
Decided not to go ahead with this at File Formats Task meeting 2021-05-27. Crucial points are that this will break current links and that if there is a move of the compiled documents, it should be to @ga4gh's web site and not elsewhere on GitHub.
