### ISSUE TITLE
`.gitignore` for `/new` and `/auto`

### ISSUE THREAD

**Issue by michaelmhoffman** [samtools/hts-specs#574]
Is there a reason why only `/new/*.pdf` is in `.gitignore` and not all of `/new`?

Also would you accept a PR adding to `.gitignore` a pattern for `/auto`, which AUCTeX creates when editing LaTeX documents ?

**Comment by jmarshall** [comment]
Instead of having a blanket ignore for the directory, _.gitignore_ ignores each of LaTeX's temporary output file extensions individually. This is so that we'll notice if new ones (re-)appear and can take action if necessary, e.g. as noted in b40213bacf0891efbcb3a405319745c1aa228a67:

> None of the documents actually have indices, so remove \makeindex from the .tex files it appears in. This reduces the number of LaTeX runs needed for BCFv2_qref and CSIv1. Don't ignore or clean .idx, as if some index reappears we'll want to know about it to add code to invoke makeindex etc.

I suppose with a move to `latexmk` some of that motivation would go away, though IMHO it's good to be explicit anyway.

Me, I wouldn't have a major objection to ignoring `/auto`, though it's a shame AUCTeX uses such a generic filename (I see it can be altered via setting `TeX-auto-local`). Other TeX editing workflows probably also have their own temporary directory names, so there's a point of view that this is a local thing that would be better ignored in your repo's _.git/info/exclude_. But probably in _.gitignore_ with a comment would be fine too.

**Comment by michaelmhoffman** [comment]
https://github.com/github/gitignore/blob/master/TeX.gitignore has a relatively exhaustive list of ignores for a TeX project that includes `./auto/*`
