### ISSUE TITLE
Request to add new one-letter base-modification codes

### ISSUE THREAD

**Issue by sathish-t** [samtools/hts-specs#658]
Hello,

I would like to request two additions to one-letter base-modification codes (ref. pg. 9 of https://samtools.github.io/hts-specs/SAMtags.pdf). Is it possible to reserve 'B' for thymidine analogue BrdU (5-bromo-2'-deoxyuridine, CHEBI: 472552) and 'E' for EdU (5-Ethynyl-2′-deoxyuridine, CHEBI:N/A)?

Many tools available right now only respond to one-letter codes. And it's not possible to combine modifications like C+mh with just the CHEBI codes.  Thanks!

Regards
Sathish

**Comment by jkbonfield** [comment]
The codes currently there were added into accordance with https://www.biorxiv.org/content/10.1101/043794v1.full-text

Do you have any literature indicating the codes B and E are standard ones?  I don't really feel qualified to be the arbiter of what's valid and what isn't as a code, and would probably just defer to the authors of the previous paper (for example).

I'm also somewhat wary of adding things that don't even yet have an entry in CHEBI.  I think first up we should be getting them listed in the primary database first.

**Comment by jkbonfield** [comment]
At our last conference call I think the general consensus was we (the spec maintainers) shouldn't be the ones deciding on nomenclature and abbreviations.  We would advise direct communication with the CHEBI team and perhaps the originators of the existing accepted abbreviations (see paper above).

We will however naturally follow any community lead acceptance of new terms and update the spec to follow this, rather than lead.

**Comment by jkbonfield** [comment]
I'm closing this as for now we have no intention on playing arbiter of which codes to permit, and will instead wait for community consensus on such matters.  When there are widely accepted new codes we will be happy to update the SAM specification to accommodate them.  Please create a new issue if and when this situation arises.
