### ISSUE TITLE
VCF 4.4: calculate END from SVLEN

### ISSUE THREAD

**Issue by tcezard** [samtools/hts-specs#672]
Section [3 in VCF 4.4](https://github.com/samtools/hts-specs/blob/59a0d0c8dc01b46192f6da1cec61db59c9b3d1d9/VCFv4.4.draft.tex#L688) specifies that `END` can be calculated from `POS + SVLEN` but as far as I understand that would not work for insertion. 
In the example provided [here](https://github.com/samtools/hts-specs/blob/59a0d0c8dc01b46192f6da1cec61db59c9b3d1d9/VCFv4.4.draft.tex#L1131)
```
chrA   14  .    T   <INS>     .    .      IMPRECISE;SVLEN=100;END=14 GT    0/1
```
If END was absent it would be calculated as `END = POS + SVLEN = 14 + 100 = 114`

Does this make sense ?

**Comment by d-cameron** [comment]
It's also wrong for DUP and CNVs as if there's a DUP/CNV that increases in
more than one multiple (e.g. going from 1 copies to 3 tandemly duplicated
copies) the SVLEN should still encode the end position in the reference,
not the longer length of the alt allele. I'll rewrite the definition of
SVLEN since the current wording is wrong in multiple ways.
