### ISSUE TITLE
cram: Explain the layout of the raw SAM header in the CRAM header container

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#678]
This is regarding _CRAM format specification (version 3.0)_ (2022-08-15).

§ 7.1 "CRAM header container" does not explain the layout of the raw SAM header, specifically that it is length-prefixed. Emperically, it seems to be `<length><raw header text>[optional null padding]`, where `length` is a signed(?) 32-bit integer. Some implementations (e.g., [CRAMTools](https://github.com/enasequence/cramtools/tree/cram3)) do not use a new block for padding but instead pad the raw header text, which requires the data to be trimmed to `length`.

**Comment by jkbonfield** [comment]
In my code for reading this I have a comment:

https://github.com/samtools/htslib/blob/develop/cram/cram_io.c#L4694-L4701
```
        if (-1 == int32_get_blk(b, &header_len) ||
            header_len < 0 || /* Spec. says signed...  why? */
```

Clearly at some point there was a bit of specification stating the header starts with a 32-bit signed value indicating the length of it.  Maybe this got removed by accident at some point.  I cannot find any trace of this though.  Not even in my old copy of CRAMv1.1!  I'm not sure where that came from, but the comment was originally added by @daviesrob after fuzzing.

This is one of the many things would should be fixed in the mythical CRAM v4.  (Are you up for it?)
