### ISSUE TITLE
Best encoding for use case

### ISSUE THREAD

**Issue by rmhubley** [samtools/hts-specs#706]
Here is my use case.  I would like to store 3-4k reads in a CRAM file.  Each read may be mapped to anywhere between 3-10M locations (partial alignments included) in a given reference assembly.  Since the read is a fixed length sequence ( anywhere between 100bp - 20kb ), what is the most efficient way to encode this using the CRAM specification (e.g as secondary reads, or read groups etc) and what libraries would be most efficient at building a CRAM file (ie. not going through SAM format first).  Perhaps CRAM isn't designed (currently) to store generic alignments like this.

**Comment by jkbonfield** [comment]
At say 4k reads and 5M locations, that's 20 billion alignments.  That's quite a lot!  May I ask what problem this experiment is solving?  If you can't answer that, then maybe something about the nature of the multiple hits.  Is each of the 4k reads going to have its own distribution of 3-10M mapping locations, which would become a vast reference genome, or are there likely to be many original reads sharing the same mapping locations?  Eg 10M sites with each site sequenced to great depth from many reads?

Also why are there so many mapping locations? How many of those sites are identical sequence to each other?  Clearly some must be, as we can't have a single read with different sub-strings each matching to a different site, unless we've broken the world record for the longest read by a couple orders of magnitude.  The reason this matters is it changes the compression.  Many identical sequences and identical starting coordinates offers much greater compression ratio than a very diverse mapping location and sequence.

Multiple locations is usually secondary alignment if it's the same sub-string matching, or supplementary alignments if it's a different sub-string matching, so that seems like the logical way to go.  Adding them as a read-group wouldn't particularly change things, but neither would it be harmful I think.  I am assuming you would not be filling out SA/XA tags or similar for describing the other alignments, otherwise you have an N^2 size growth thing going on.

CRAM doesn't have any special approach for handling millions of secondary alignments. Are your reads is pairs?  It may get a bit hairy if there are millions of pairs all with the same name, if they're not labelled as secondaries.  If it's all single ended then the read-pairing logic (setting TLEN, MRNAME and MPOS) doesn't come into play so we wouldn't need to be concerned about that.  It's not something I've tested though.  Given the number of variables involved, all I can suggest is trying it out and exploring the size of the resulting cram using io_lib's cram_size tool or the (soon to be) samtools cram-size subcommand.

As for which library to use, this repository is more focused on specifications than implementations, but naturally I'm biased and would say I believe the htslib implementation to be the most performant.  Internally it represents sequence data in an uncompressed BAM-ish representation, which can be created programmatically using `bam_set1`.  That object can then be written directly to CRAM which will do the format conversion for you.

**Comment by rmhubley** [comment]
Ha!  I am perfectly happy divulging the use case.  I am evaluating CRAM as a possible container for raw genomic alignments of to libraries of transposable element family consensi (not reads). The scale is a bit exaggerated if one assumes all families have 5M copies, whereas for most species, the families will have 100s to 1000's of copies and only the rare cases are they as abundant as the 1M-10M scale.  The big caveat is that we store all alignments significant alignments down to a noise threshold even if they overlap with other families (e.g. the raw output of the alignment process).  For example, this amounts to 93M alignments for Human and 73M for Mouse. 

So, while not reads these are essentially a very similar use-case.  The locations are each of the potential (full/partial) copies of a family in the genome and vary widely in divergence from the consensus.  So except for the youngest families you won't expect identical matches.  For compression this is ideal as the SEQ fragment recorded for each "read" is a subsequence of a consensus and therefore highly redundant.  For that same reason re-recording the consensus at all in each 'read' is silly as it is unnecessary so I could simply leave SEQ as undefined ('*') and leave the burden of alignment reconstruction to downstream processing (CIGAR + library + reference).

In a sense my data might technically fall into both the Secondary and Supplementary category as you describe them.  For instance, I will definitely find alignments to the same substring of a given family consensus.  Is there any problem with encoding those as Supplementary?  While one could conceive two (or more) co-linear alignments to a given family as a 'read-pair', luckily I am not leaning on this file format to hold that sort of data so the read-pairing fields would not be necessary.

Thanks for your feedback.  I probably should have been more specific about my query in the first place.  I could roll-my-own format for storing this data and very well might end up doing that, but I like the way CRAM is going and I don't see any reason why this couldn't be a more general alignment storage format going forward.  Mostly I wanted to make sure there wasn't something I was missing that would make my use-case more efficient.  Using pysam I converted a TSV alignment set of 73M alignments in CIGAR + SEQ ( 49 GBytes ) to CRAM ( 7.7 GBytes ) in 6 hours -- I figure it will be much faster in htslib.

**Comment by jkbonfield** [comment]
Thanks.  It doesn't sound as extreme in the usual case then, just a very broad range and heavily skewed to the lower end.

Note you may not need to worry too much about having SEQ vs * if the sequence is a very close match to the "reference", as it will just get removed by the SEQ/REF delta algorithm.  If you have reference being one thing and everything aligned against it at a particular locii differing (eg a specific sample vs grch38), then you'll end up having to encode that difference repeatedly, both in SEQ and/or MD:Z tags.

Hence the other thing worth investigating is embedding the consensus as the reference.  Htslib has had improvements in usability here and with the upcoming 1.17 release will make this more streamlined.  It can be enforced (currently develop branch, and then 1.17) with e.g.:

```
samtools view -O cram,embed_ref=2 -o out.cram in.sam
```

(With the latest code, that also becomes the norm also if it fails to find the external reference, albeit with a whinge to let you know it's changing behaviour.)

This forces it to compute the reference, either from SEQ+MD:Z tags, or if we omit the MD:Z and NM:i tags it'll derive the reference directly from the aligned SEQ fields.  The CRAMs take up more room to store the actual reference internally, but it's  usually a tiny percentage once you get to sufficient depth.  This also opens up avenues of designing your own clustering and reference mechanisms without having to supply that custom external reference along side the CRAM.

From my testing, it appears htsjdk is also supporting embedded references well now, including ones with md5sums that differ to the official external reference for that slice. (That was an issue with older releases.)  So it should be a robust technique to try out.

**Comment by rmhubley** [comment]
I agree that using the consensus as my reference makes sense from a compression standpoint.  The consensus is the theoretical distance centroid and thus minimizes the differences encoded.  However, my primary use case is querying this data by genomic region and not by consensus, wouldn't reversing the sequences make those searches much slower?

**Comment by jkbonfield** [comment]
When CRAM uses an embedded consensus, it is expected that the consensus is still in reference coordinates.  So it's not a true consensus with regards to indels.  This means that the genomic coordinates won't change and querying can be done as before.  The intention really is simply to allow an external reference free way of decoding CRAM.

**Comment by jkbonfield** [comment]
Closing, as this was an answered question rather than an "issue".
