### ISSUE TITLE
Interaction of POS and soft-clipping is unclear

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#80]
When an alignment starts with some soft clipping, e.g. CIGAR is `3S7M`, the spec is unclear whether POS is the location of the first base in SEQ or the fourth (i.e., the first unclipped base).

Studying htslib's `bam_cigar2rlen()` and `bam_cigar_type` suggests that it is the first unclipped base, as only M/D/N/=/X operators consume reference bases.

This interpretation is implied by §2 4(3) (which discusses best practices for mappings that exceed the length of the reference sequence).  It can be inferred from the description of POS:

> POS: 1-based leftmost mapping POSition of the first **matching** base

but it would be helpful to expand on exactly what _matching_ implies here.

**Comment by nh13** [comment]
Are you referring to ```SEQ```as the bases sequenced or the bases covered in the reference?  I think you are saying the former, and I would agree here.

**Comment by jmarshall** [comment]
I'm referring to the SEQ column.

**Comment by jkbonfield** [comment]
On Wed, Apr 01, 2015 at 01:59:52PM -0700, John Marshall wrote:
> This interpretation is implied by ?2 4(3) (which discusses best
> practices for mappings that exceed the length of the reference
> sequence).  It can be inferred from the description of POS: 
> 
> > POS: 1-based leftmost mapping POSition of the first **matching** base
> 
> but it would be helpful to expand on exactly what _matching_ implies here.

I've always took this interpretation too and I think it is reasonably
clear, but perhaps needs to be more explicit and shouldn't just be
part of the best practices section.

More interesting is the case of 3I7M.  The I bases don't match (the
reference) either so in that respect they have the same identical
problem as 3S6M.  We need to remember that when clarifying the meaning
of POS.

In pairwise seq vs ref alignments these things do not occur, but in a
multiple alignment they may. Eg:

        123456     789012
    Ref ATTAGC-----GCAGCT
    Seq ATTAGCTTATTGCAGCT       6M5I6M
    Seq  TTAGCTTATTGCAGCT       5M5I6M
    Seq    AGC--ATTGCAGCT       3M3I6M
    Seq      CTTATTGCAGCT       1M5I6M
    Seq         ATTGCAGCT         3I6M

The last 3I6M is clearly the correct multiple alignment, but also
clearly it we have trouble indicating that it starts at position 7.
It starts *before* 7 and after 6, which incidentally makes mpileup
fail to include the insertion too.

Further more there is no indication of the "binding" of those bases.
Obviously here 3I6M means there are 3 bases just prior the 6M.  6M3I
would imply 3 bases just after 6M.  What about the 3M3I6M example?  It
shows there are 3 bases *between* the 3M and 6M, but we don't really
know where.  In isolation, a pairwise alignment, they bind on to the
3M and 6M.  In a multiple alignment we would require 3M2P3I6M to
correctly explain how it aligns in relation to the other sequences
rather than just the reference.

Should it be mandatory to add 2P before the last 3I6M if we want to
describe a true multiple sequence alignment (IMO yes), or is it
sufficient to assume left/right binding as it is the first/last
insertion?  This is perhaps a bit out of the scope of your issue
though.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by AndrewUzilov** [comment]
I second @jmarshall for request for clarification.  My own issue, which I raised elsewhere (https://github.com/igvteam/igv/issues/145 ) before I stumbled across this one, had to do with how to interpret `POS` if there is a leading `D` operation (e.g. the whole CIGAR is`8D10M`).  In this case, does `POS` refer to `8D` or `10M`?

My interpretation of the spec was that `POS` refers to `10M`.  IGV's interpretation, also Heng Li's and several others, is that it refers to `8D`.  See the discussion thread on the samtools-devel@lists.sourceforge.net list started today:
http://sourceforge.net/p/samtools/mailman/samtools-devel/?viewmonth=201505&style=flat

**Comment by peterjc** [comment]
Further to James' (@jkbonfield) comments about the need for the CIGAR P operator to make many examples unambiguous, see also our preprint:

> SAM/BAM format v1.5 extensions for de novo assemblies.
> Peter J. A. Cock, James K. Bonfield, Bastien Chevreux, Heng Li.
> bioRxiv DOI: 10.1101/020024
> http://dx.doi.org/10.1101/020024
> http://biorxiv.org/content/early/2015/05/29/020024

Announced on the mailing list today: http://sourceforge.net/p/samtools/mailman/message/34161881/
